### ISSUE TITLE
tab completion is borked

### ISSUE THREAD

**Issue by groner** [Keeper-Security/Commander#1014]
In the keeper commander shell, when I enter `cc ` followed by the first few characters of a record title, I no longer see just the records that start with those leading characters.

It just shows everything now.

It's not even sorted.

**Comment by sk-keeper** [comment]
Thank you for reporting this issue. It will be fixed in the next Commander release later this week.

**Comment by groner** [comment]
Things are better again with 16.9.3. Thanks.

#378 is still outstanding.
