### ISSUE TITLE
Login with SSO

### ISSUE THREAD

**Issue by joe-avb** [Keeper-Security/Commander#1026]
Ubuntu 23.04 running keeper in a venv

When logging in via SSO, I am unable to paste the SSO token from the clipboard. I'm getting the error message "Failed to paste from clipboard"

I never had this issue until 23.04 made it mandatory to run pip in a venv

Ubuntu 23.04
Python 3.11.2
pip 23.0.1

**Comment by sk-keeper** [comment]
Commander uses `pyperclip` package to work with clipboard.
https://github.com/asweigart/pyperclip
```
On Linux, this module makes use of the xclip or xsel commands, which should come with the os. Otherwise run "sudo apt-get install xclip" or "sudo apt-get install xsel" (Note: xsel does not always seem to work.)

Otherwise on Linux, you will need the gtk or PyQt4 modules installed.
```
