### ISSUE TITLE
MSP Info - Output

### ISSUE THREAD

**Issue by davewatson91** [Keeper-Security/Commander#1047]
Hi team, 

When trying to use the msp-info command, I am unable to output this in a similar fashion to other commands, whereby I cannot format it as JSON or anything - somehow it won't even allow me to assign it to a variable, and simply will only print. 

The outcome I am trying to achieve, is to setup automated billing - unfortunately my billing system can only accept proration based on a (near) real time update - where it just wants to track the actual number of licenses (and not the average for the previous month). 

Hoping for some guidance please. 

Cheers, 
Dave

**Comment by sk-keeper** [comment]
Thank you for reporting this issue. `msp-info` command will add `--format` argument as any other report command.
The fix is already checked in to the release branch.

**Comment by davewatson91** [comment]
Thanks so much @sk-keeper - incredibly quick, really appreciate it. 

On what schedule does the release branch form an actual release normally? (Just whether it's worth me waiting for the actual 'release'. 

Thanks again!

**Comment by aaunario-keeper** [comment]
You can download the appropriate installer (or source code if you prefer) via https://github.com/Keeper-Security/Commander/releases/tag/v16.9.7

You can also re-install the app via pip (w/ the -U flag to update to the most recent version: **16.9.7**)
Hint: calling the Keeper command 
`version -v
`
will output the currently-running Commander version.

To answer your question more directly: just make sure to update your current Commander install (via one of the above methods) and `msp-info` should work as expected.

**Comment by sk-keeper** [comment]
The beta release can be downloaded here
https://github.com/Keeper-Security/Commander/releases/tag/v16.9.8

**Comment by davewatson91** [comment]
Ah great, really appreciate it thanks!!
