### ISSUE TITLE
Using CLI in shell scripts

### ISSUE THREAD

**Issue by carlosabalde** [Keeper-Security/Commander#1050]
I've recently moved from 1Password to Keeper and I'd like to integrate `keepercommander` into a few shell scripts for automation purposes, the same way I did with 1Password. Nothing fancy. Just fetching a password, TOTP, user, etc. from stdout and storing it in an environment variable, to be later used with tools like `expect`. Something like `PASSWORD=$(keeper clipboard-copy ... --output stdout)` would do the job... unless authentication (i.e. login, SSO, TOTP...) is required. Ideal behavior would be to handle authentication out-of-band (e.g. separate popup window), but simply failing would be good enough for most scripting purposes (i.e. the script would fail, the user would manually run `keeper login`, and then the user will retry).

Problem is current behavior would block execution waiting for input (and nothing would be rendered in the terminal because we are capturing output). Only alternative I can think of is to use `tee`, but that's not ideal because the password would be rendered in the terminal. In summary, the failing-if-not-authenticated approach seems to be the best option, but it doesn't seem to be supported by the CLI. Any suggestions on how to implement this?

**Comment by carlosabalde** [comment]
Finally I've created a dirty wrapper for `keepercommander`. Basically it behaves like `keeper clipboard-copy ... --output stdout` but:
- On success (i.e. exit code == 0) it only outputs the password, TOTP, etc. to stdout. All other output goes to stderr.
- On failure (i.e. exit code != 0) it gives you the chance to provide the password, TOTP, etc. manually (or to abort).

The really important part is the behavior on success, ensuring that the password, TOTP, etc. is the only output in stdout, which allows a friendly integration in scripts. It's done the only way I could find in the CLI: using the clipboard to transport the result and use `tee` to move all other output (i.e. connection to the SSO, etc.) to `stderr`, which is ugly but it works.

```bash
#!/usr/bin/env bash

if [ "$#" -ne '2' ]; then
    echo 'WTF!?' >&2
    exit 1
else
    RECORD_PATH_OR_OID=$1
    RECORD_FIELD=$2
    case "$RECORD_FIELD" in
        login|totp)
            KEEPER_ARGS="--$RECORD_FIELD"
            READ_ARGS=''
            ;;

        password)
            KEEPER_ARGS=''
            READ_ARGS='-s'
            ;;

        *)
            echo 'WTF!?' >&2
            exit 1
            ;;
    esac
fi

OUTPUT=$(keeper clipboard-copy "$RECORD_PATH_OR_OID" $KEEPER_ARGS 2>&1 | tee /dev/stderr; exit ${PIPESTATUS[0]})
if [ $? -ne 0 ]; then
    echo "Failed to fetch '$RECORD_FIELD' from '$RECORD_PATH_OR_OID'!" >&2
    while true; do
        read $READ_ARGS -p "Enter '$RECORD_FIELD' value manually: " VALUE >&2
        if [ -n "$VALUE" ]; then
            break
        fi
    done
else
    VALUE=$(xclip -selection clipboard -o)
    echo -n '' | xclip -selection clipboard -i >&2

    echo -n "Fetched '$RECORD_FIELD' from '$RECORD_PATH_OR_OID': " >&2
    if [ "$RECORD_FIELD" == 'password' ]; then
        printf '%*s\n' "${#VALUE}" | tr ' ' '*' >&2
    else
        echo "$VALUE" >&2
    fi
fi
echo -n "$VALUE"
```

I'd love to hear about a better way to do this, but I'm not sure if it's possible. Btw, in 1Password this is simpler because the CLI uses a PolicyKit authentication agent integrated with the Desktop app. That way, the authentication mumbo-jumbo is handled by the Desktop app and the CLI only needs to ask for the password, TOTP, etc.

**Comment by craiglurey** [comment]
Hi @carlosabalde did you look at the Secrets Manager SDKs? These are more targeted towards retrieving records from the vault in a fast and efficient way.

https://docs.keeper.io/secrets-manager/secrets-manager/overview

The CLI can be used to retrieve data in any format such as JSON:
https://docs.keeper.io/secrets-manager/secrets-manager/secrets-manager-command-line-interface/secret-command

**Comment by carlosabalde** [comment]
Mmm... I didn't look into Keeper Secrets Manager, but it looks like that's a separate non-free product (right now I'm doing my tests with Keeper Enterprise), right? I guess I'll need to stay with my poor man's approach then :)

**Comment by carlosabalde** [comment]
I've confirmed with @craiglurey Keeper Secrets Manager is an add-on to the enterprise version. That's they way to go for serious integrations, but for my use case the poor man's approach is sad & slow... but good enough. Thanks!
