### ISSUE TITLE
Missing example config.json for python auth

### ISSUE THREAD

**Issue by Luke-Williams9** [Keeper-Security/Commander#1052]
Or maybe I'm missing it?
I found a good example here:
https://pypi.org/project/keepercommander/0.6.5/

{
    "server":"https://keepersecurity.com/api/v2/",
    "user":"your_email_here",
    "password":"your_password_here",
    "debug":false,
    "commands":[]
}

Would be nice to to include a substantial example config in the examples directory.

**Comment by sk-keeper** [comment]
Configuration file format is documented here
https://docs.keeper.io/secrets-manager/commander-cli/commander-installation-setup/configuration

**Comment by Luke-Williams9** [comment]
Thanks.... not sure how I missed that
