### ISSUE TITLE
Allow MariaDB rotation with MySQL plugin

### ISSUE THREAD

**Issue by ogowen45** [Keeper-Security/Commander#1066]
By changing the current lines 54-63 in mysql.py from the below:

 if affected == 1:
                    rs = cursor.fetchone()
                    version = rs[0]     # type: str
                    vc = version.split('.')
                    vn = 0
                    if len(vc) == 3:
                        for n in vc:
                            vn *= 1000
                            vn += int(n)
                        is_old_version = vn < 5007006

to:

                if affected == 1:
                    rs = cursor.fetchone()
                    version = rs[0]     # type: str
                    main_version = version.split('-',1)[0]
                    vc = main_version.split('.')
                    vn = 0
                    if len(vc) == 3:
                        for n in vc:
                            vn *= 1000
                            vn += int(n)
                        is_old_version = vn < 5007006

It allows it to handle MariaDB versions to then rotate the password as expected.

**Comment by sk-keeper** [comment]
Thank you for letting us know about MariaDB version format differences.
The next release will include this fix.
https://github.com/Keeper-Security/Commander/commit/16b5ce41d6fdb91d62660aa39a0cc0a2a49b81fb
