### ISSUE TITLE
`get` command to only print specified field

### ISSUE THREAD

**Issue by weichuliu** [Keeper-Security/Commander#1069]
Hi,

I am a new user for Keeper and the cli.

I am embedding the cli in scripts. In most cases, I want to get the raw secret **and the raw secret itself only**. However, `keeper get` prints a lot of metadata and the behavior is not configurable.

The best I can do is 

```
keeper get UID --format json | jq -r '.fields | .[] | select( .type == "note") | .value | first'
```

which makes the task complicated and ugly.

Can `get` add a flag to support printing raw secret, with specified filed?

**Comment by craiglurey** [comment]
Hi @weichuliu we'll discuss and come up with a solution for you.

**Comment by sk-keeper** [comment]
`clipboard-copy` command supports `--field` parameter. The field value can be outputted to stdout or clipbord
https://app.gitbook.com/o/-LO5CAzoigGmCWBUbw9z/s/-MJXOXEifAmpyvNVL1to/commander-cli/command-reference/record-commands#clipboard-copy-command
```
keeper cc UID --field=notes --output=stdout
```

**Comment by weichuliu** [comment]
Thanks, `clipboard-copy` works.

However, I have to say using `clipboard-copy` here is very confusing...

**Comment by sk-keeper** [comment]
Commander's `get` command accepts any UID and returns object (record, shared folder, team, ...) information.
We would not like to add record specific options to this command.
`clipboard-copy` works with records only.
`clipboard-copy` command has an alias `find-password`. It is not intuitive either.

**Comment by weichuliu** [comment]
Oh the `find-password`, the naming makes much more sense to me. Also by default it prints to stdout than clipboard.

The reason why I didn't realize in the first place is because the `find-password` as an alias is not displayed in `keeper help`.

I really think it's worth mentioning this subcommand in `keeper help`, and describe the relation between `clipboard-copy` and `find-password` under `clipboard-copy`'s explanation text.

**Comment by weichuliu** [comment]
Anyways, my question about why `get` doesn't work is explained, so I'll close this ticket.

Thank you!
