### ISSUE TITLE
Keeper Commander pip3 fails to install on Windows ARM64 - "Unable to find vcvarsall.bat"

### ISSUE THREAD

**Issue by TBSJordanNash** [Keeper-Security/Commander#1083]
Keeper Commander pip3 fails to install on Windows ARM64 - "Unable to find vcvarsall.bat" 

Windows ARM64, local user Python install, with path.
![Screenshot 2023-08-30 120445](https://github.com/Keeper-Security/Commander/assets/103598158/1a5686df-a097-42a5-ab63-88101c5c587a)

The most relevant error message seems to be: "Unable to find vcvarsall.bat"

This link may be helpful? https://learn.microsoft.com/en-us/cpp/build/building-on-the-command-line?view=msvc-170#developer_command_file_locations

Full log:
[20230830_keeper_pip_install_failure.txt](https://github.com/Keeper-Security/Commander/files/12478634/20230830_keeper_pip_install_failure.txt)

**Comment by TBSJordanNash** [comment]
PS C:\Users\user.name> $env:PATH
C:\Program Files\WindowsApps\Microsoft.PowerShell_7.3.6.0_arm64__8wekyb3d8bbwe;C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_1.17.11461.0_arm64__8wekyb3d8bbwe;C:\Program Files\Parallels\Parallels Tools\Applications;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\WindowsPowerShell\Scripts;C:\Users\user.name\AppData\Local\Programs\Python\Python311-arm64\Scripts\;C:\Users\user.name\AppData\Local\Programs\Python\Python311-arm64\;C:\Users\user.name\AppData\Local\Programs\Python\Launcher\;C:\Users\user.name\AppData\Local\Microsoft\WindowsApps;C:\Users\user.name\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\user.name\AppData\Local\Programs\Git\cmd

**Comment by TBSJordanNash** [comment]
Hopefully, the Keeper team can find a work-around for this and we aren't stuck until external dependencies are updated for ARM64 paths.

**Comment by TBSJordanNash** [comment]
I purged pip cache and attempted to install cryptography directly in verbose mode.

Log attached.

[20230830_cryptography_install_failure.txt](https://github.com/Keeper-Security/Commander/files/12478840/20230830_cryptography_install_failure.txt)

Next, I will look further into why the cryptography package is broken on ARM64.

**Comment by TBSJordanNash** [comment]
https://cryptography.io/en/latest/installation/#building-cryptography-on-windows

Checking the cryptography documentation

**Comment by TBSJordanNash** [comment]
I asked the cryptography project to offer an ARM64 static build. 
https://github.com/pyca/cryptography/issues/9519

**Comment by sk-keeper** [comment]
There were similar requests in the past
https://github.com/pyca/cryptography/issues/8148
