### ISSUE TITLE
missing --legacy option

### ISSUE THREAD

**Issue by StefanoThS** [Keeper-Security/Commander#1139]
Commit #317eceb (Support Share Admin. KC-390) removed the --legacy option.
Is it possible to restore it? In out company's keeper vault, we have a mix of new and legacy record and relied on this option to be able to parse the output json with the same structure. That change broke our company IaaC scripts, so we are still using commander version 16.7.9

**Comment by sk-keeper** [comment]
Thank you for reporting this issue. We could not predict the result of removing this option.
This option will be put back in the next Commander release.

**Comment by StefanoThS** [comment]
I just tested the 16.9.28 release. Everything works fine for me, now. Thank you very much!
