### ISSUE TITLE
Enhance "automator log" command to actually download or display the logs

### ISSUE THREAD

**Issue by jeff-stieglitz** [Keeper-Security/Commander#1166]
In my shop I don't have direct access to the automator docker container so I need to ask the devops admin guys to ship them to me. 

The automator section of the commander documentation [at this link](https://docs.keeper.io/secrets-manager/commander-cli/command-reference/enterprise-management-commands#automator-command) is brief - all it says for the log command is "Retrieves automator logs", but in practice it seems that the command doesn't retrieve the automator logs, it apparently displays recent errors even though I've never seen any.

I'm looking for some additional capabilities within automator to give me confidence than it is working and to assist with troubleshooting.  I'd like the "automator logs" command to download the logs in a file or just display them so I can capture them in the shell.  Maybe a parameter to give a maximum number of lines, sort of like the unix tail command.

**Comment by sk-keeper** [comment]
This request is forwarded to the automator team
