### ISSUE TITLE
add "automator reboot" to commander

### ISSUE THREAD

**Issue by jeff-stieglitz** [Keeper-Security/Commander#1168]
I see that there is a reset command, but that appears to reset the configuration to default.

To aid with troubleshooting, it would be nice if an automator restart could be triggered from commander.

I was also thinking about naming this proposed command "automator restart".

Maybe the existing "automator init" actually restarts automator, it's not clear to me if the init command is the same as a restart and if that is the case perhaps the documentation could be updated to clarify that "automator init" is a simple restart without potentially harmful setting changes.

**Comment by sk-keeper** [comment]
It is unlikely that the automator team implements this request.

**Comment by jeff-stieglitz** [comment]
Hi Sergey, thank you for letting me know.

I hope they consider the suggestion - it seems to me that it's not very
strange to remotely restart a node in a distributed system.

Jeff
