### ISSUE TITLE
Programmatic Password Rotation Saying - Password is too short

### ISSUE THREAD

**Issue by BrennanWoodbury** [Keeper-Security/Commander#1235]
When programmatically rotating a password with PAMGatewayActionRotateCommand() I'm getting this error when querying the job status via commander: 

```
-------------------------
        Status              : finished
        Duration            : 0:00:00.894716
        Response Message    : The password is too short. Minimum character length is 8.

```

My assumption is that unless you somehow inject pwd complexity into the params, it should inherit the password complexity from the web gui. 

Here's my code in question: 

```
        name = name.lower()
        uid = get_secret_uid(name)
        api.login(my_params)
        if not my_params.session_token:
            exit(0)
        api.sync_down(my_params)
        rotate = PAMGatewayActionRotateCommand()
        rotate.execute(my_params, record_uid=uid)
```

I've verified that the UID is correct, and my_params is printing out showing what I assume to be a very long list of params when printed with __dict__. I'm at a loss as to how this is happening, this code was working before the newest KCM update, I'm wondering if it is related.

Please let me know if you need any further information, I'm happy to provide whatever you need.

**Comment by sk-keeper** [comment]
Commander release 16.10.14 fixes this issue.
