### ISSUE TITLE
Enterprise Team Issue

### ISSUE THREAD

**Issue by JimPahlAtSkyline** [Keeper-Security/Commander#126]
The EnterpriseTeamCommand is not working. It appears the register_commands in enterprise.py may be misaligned.

PS> Set-KeeperEnterpriseTeam -Identity 'Test_001'

cmdlet Set-KeeperEnterpriseTeam at command pipeline position 1
Supply values for the following parameters:
AuthObject
Traceback (most recent call last):
File "C:\Program Files\WindowsPowerShell\Modules\keepersecurity.powershell\PyScripts\Set-KeeperEnterpriseTeam.py", line 8, in 
from keepercommander.commands.register import EnterpriseTeamCommand
ImportError: cannot import name 'EnterpriseTeamCommand' from 'keepercommander.commands.register' (C:\JPStuff\Client Care\KeeperCommander\WPy64-3720\python-3.7.2.amd64\lib\site-packages\keepercommander\commands\register.py)

**Comment by craiglurey** [comment]
We will check this and resolve.  Thanks Jim

**Comment by JimPahlAtSkyline** [comment]
What is the ETA on the next PyPI update for Keeper Commander?

Thank you,
Jim Pahl | Senior Software Engineer
Office: (920) 593-3671 | Mobile: (920) 213-1856
jpahl@skylinetechnologies.com<mailto:jpahl@skylinetechnologies.com>
100 W Lawrence Street, Appleton, WI 54911
[Email-Signature-Logo2]<https://www.skylinetechnologies.com/>
  [Email-Signature-Facebook] <https://www.facebook.com/SkylineTechnologiesInc>  [Email-Signature-Linkedin] <https://www.linkedin.com/company/skyline-technologies>  [Email-Signature-Twitter] <https://twitter.com/skylinetweets> [Email-Signature-Email] <https://www.skylinetechnologies.com/subscription>

**Comment by craiglurey** [comment]
I'll push it today.

**Comment by craiglurey** [comment]
Done
