### ISSUE TITLE
Cannot import keepass db with attachments

### ISSUE THREAD

**Issue by jdall** [Keeper-Security/Commander#131]
When trying to import a keepass database containing attachments, I get the following output:

> Processing... please wait.
> ...    Keepass Password: 
> Uploading attachments:
> NetBackupEnc.key ... Done
> Can't convert 'bytes' object to str implicitly
> 
> Goodbye.
> 

Running Keeper Commander, version 4.0

Please fix.

Thanks.

**Comment by craiglurey** [comment]
We'll fix today.

**Comment by craiglurey** [comment]
Fixed.  Deploying pip3 in a minute.

**Comment by craiglurey** [comment]
PyPi pushed to version 4.1.

**Comment by jdall** [comment]
Thank you very much for a quick fix. The app works like a charm now.
