### ISSUE TITLE
keepass import not importing attachments

### ISSUE THREAD

**Issue by bruno-sardine** [Keeper-Security/Commander#1332]
**Commander Version**: 16.11.20 (Current version)
**OS**: MacOS Sequoia 15.1 
**KeePass Database Format**: KeePass 2
**Python** 3.8.5
**pip** 24.3.1
**pip3 show pykeepass** = Version: 4.1.0.post1

Commmand:
```
Syncing...
Decrypted [1] record(s)
My Vault> import --format=keepass /Users/cmench/Downloads/example.kdbx
Processing... please wait.
...    Keepass Password: 
Press Enter if your Keepass file is not protected with a key file
...    Path to Key file: 
folder          success         1
legacy record   success         1
Uploading attachments:
KeeAgent.settings ... Done
pngwing.com.png ... Done
id_ed25519 ... Done
My Vault>
```

example.kdbx contains a single attachment.  The record is imported, but the attachment is missing. 
![noattachment](https://github.com/user-attachments/assets/e6d8409a-b273-4dc8-95b0-43d06b32532b)

If  I create a record with an attachment in Keeper Password Manager and issue `export --format=keepass`, the attachment is available in tools like KeePassXC

Despite the attachment "pngwing.com.png" being processed, it's nowhere to be found in Keeper Password Manager

example.kdbx here.  password is password123
[https://drive.google.com/file/d/1sR7jZast1e_YSJvLXoB9SvuX8vMR7jFi/view?usp=sharing](url)

**Comment by sk-keeper** [comment]
Thank you for reporting this issue. It will be fixed in the next release.
You can use `--login-type` option to force Keeper to import records in the new format.
```
--login-type, -l      import legacy records as login record type
```

**Comment by bruno-sardine** [comment]
confirmed `--login-type` works.   thank you!
