### ISSUE TITLE
connect / listing connections in folders

### ISSUE THREAD

**Issue by lsntomaszw** [Keeper-Security/Commander#161]
currently ``connect`` method lists all the connections in all folders

1. its semi-useful when its sorted first by endpoint name (folder, endpoint name would work much better)

![image](https://user-images.githubusercontent.com/5519743/62786560-25f96080-bac3-11e9-9761-db610c01080a.png)

2. any chance for some filters like connect ``*ehp*`` just to limit the output to /lsn/ehp/ folder?

**Comment by craiglurey** [comment]
Done
