### ISSUE TITLE
Can't import JSON data - Incorrect AES key length (86 bytes)

### ISSUE THREAD

**Issue by alexpilon666** [Keeper-Security/Commander#169]
Hi!
Trying to use the Import feature to create new shared folders in Keeper Cloud, but it keeps returning the following error: `Incorrect AES key length (86 bytes)`

I initially thought it was my code, so I did a JSON dump of an existing folder/record set, deleted those records, and then tried to import the dumped JSON as-is, and I got the same error.

Steps followed:
```
keeper shell
[login using non-SSO Keeper Administrator]
export --format json keeper_export.json
import --format json keeper_export.json
Incorrect AES key length (86 bytes)
```
This happens whether I do the import command as a one line (i.e: `keeper --user someuser --password somepassword import --format json somefilepath.json`) or whether I log into keeper shell and trigger the import from there.

This is the Python code I'm using for reference: 

```
#!/usr/bin/python3
import os
import subprocess
import json
folders = ['SomeFolderName', 'SomeOtherName', 'Potato', 'Potahto']
filepath = "keeper_new_folder.json"
for folder in folders:
    try:
        os.remove(filepath)
    except:
        print("File not exist, cannot delete")
    data = {}
    data['shared_folders'] = []
    data['shared_folders'].append({
        'path': folder,
        'manage_users': 'true',
        'manage_records': 'true',
        'can_edit': 'true',
        'can_share': 'true',
        'permissions': [
            {
                'name': 'SG.SLTECH.DEVOPS',
                'uid': 'Ce6tm32Po81z3Y2zK5Wd3A',
                'manage_users': 'true',
                'manage_records': 'true'
            }
        ]
    }) 
    with open (filepath, 'w') as outfile:
        json.dump(data, outfile)
    subprocess.call(["keeper", "--user", "some-non-SSO-user", "--password", "somepassword", "import", "--format", "json", filepath])
```
Environment information:
- Python v3.6.8 (Ubuntu) & 3.7.3 (Windows)
- OS: Ubuntu 18.04.x LTS running on Windows 10 WSL v1 & Powershell 5.1.17134 running on Windows 10 18.03
- Keeper commander v4.12

Thanks!

**Comment by alexpilon666** [comment]
`keeper shell` does not crash nor return any errors on its own, except the `Incorrect AES key lenght (86 bytes) when importing data.
My vault is working fine, I can add/create/delete records without any issue.
Via `keeper shell`, I can export content of the vault. But importing data fails.

**Comment by sk-keeper** [comment]
It is hard to tell what make import to fail. 
Probably, one of the folders has a corrupted key. 
Import command enumerates all folders to create a lookup.

Inside `keeper shell` when you type `tree` do you see any folder with the name looking invalid? (~20 random characters)
If you do then this folder is corrupted. I'm pretty sure the corrupted folder can be deleted and you will be able to resume import.

I'll try to duplicate this scenario.

**Comment by sk-keeper** [comment]
It's a Commander issue. It related to importing shared folder with team permissions.

**Comment by alexpilon666** [comment]
In this case, while the issue gets looked at and fixed, is it possible to create a Shared Folder without setting team or individual permissions, and then later, using `keeper share-folder`, add Team permissions ?

**Comment by sk-keeper** [comment]
Yes, sure. Just do not add permission node.

**Comment by craiglurey** [comment]
This is fixed.  Will push to PIP now as well.
