### ISSUE TITLE
clipboard-copy is difficult to use

### ISSUE THREAD

**Issue by mloffer** [Keeper-Security/Commander#174]
The clipboard-copy command seems to require:

1. Case-sensitive path
2. Case-insensitive record name

This makes finding the right record more time consuming than simply using the browser extension and using the search feature.

The clipboard-copy command would be much more useful if it could fuzzy search, just like the browser extension. E.g. I can type any piece of info (say, username) into the browser extension and it will show me all records that match. clipboard-copy could return matches if not specific enough, or copy the password if sufficiently specific to return a single record.

**Comment by sk-keeper** [comment]
clipboard-copy command supports record path autocompletion, which is case-insensitive.
It matched the start of record title, though.
Commander autocompletion is intended to work similarly to bash autocompletion.
type `cc <Tab>` to invoke command autocompletion. 


I agree that Commander would benefit from extending 'clipboard-copy'  command (as well as similar commands that expect a single record as a parameter) with search functionality.

`clipboard-copy` command would search for a record if the path does not exist.

**Comment by sk-keeper** [comment]
The change is pushed to the repository. 
`clipboard-copy` uses the same method a `search [pattern]` command

**Comment by mloffer** [comment]
Excellent. Works great. Thank you!
