### ISSUE TITLE
download-attachment -h asks for password

### ISSUE THREAD

**Issue by techieshark** [Keeper-Security/Commander#177]
When just trying to get help on a command, one would not expect keeper to ask for the password, but that is what I'm seeing (with v4.15 downloaded today). 

```
keeper download-attachment --help
Password: <entered password>
usage: download-attachment [-h] record

Download record attachments

positional arguments:
  record      record path or UID

optional arguments:
  -h, --help  show this help message and exit
```

On a related (but separate) note, `keeper download-attachment -h` does not show the subcommand help, but rather the general help.

**Comment by craiglurey** [comment]
Resolved (now use "help" command instead of -h)
