### ISSUE TITLE
download-attachment fails when UID begins with "-"

### ISSUE THREAD

**Issue by vennekilde** [Keeper-Security/Commander#190]
Any UID beginning with "-" will fail with the following message
This was tested on v4.20

`keeper download-attachment -Gd9l4daPw-fMd` (UID is from the README, simply for readability)
```
the following arguments are required: record
```

The README states that you should use a double --, when the UID begins with a -, e.g.
`keeper download-attachment -- -Gd9l4daPw-fMd`
however this has no effect on download-attachment

**Comment by craiglurey** [comment]
Fixed
