### ISSUE TITLE
Command 'add' with a password does not work

### ISSUE THREAD

**Issue by alainbodiguel** [Keeper-Security/Commander#209]
Using Keeper Commander to add a record while specifying a password (with option `--pass`) does not work (it does when using the option `-g`)
```
>keeper add --login 'test' --pass 'foo' --url 'http://google/com' 'test'  
Authentication failed.  
Password:   
AuthenticationError Error: Authentication failed.  
```

It looks like the `--pass` is wrongly interpreted as `--password` and is used to authenticate the user instead of filling the password field of the record (which you can confirm if you use your vault's password as a value for the `--pass`).

**Comment by alainbodiguel** [comment]
It looks like the problem is [here](https://github.com/Keeper-Security/Commander/blob/3f7ca720e3f6363f2b160b5659d9f57fb4c02b25/keepercommander/commands/record.py#L181).

The option should be 'pass' instead of 'password', right?

**Comment by sk-keeper** [comment]
'password' is correct at first glance
[https://github.com/Keeper-Security/Commander/blob/3f7ca720e3f6363f2b160b5659d9f57fb4c02b25/keepercommander/commands/record.py#L111](line #111)

**Comment by sk-keeper** [comment]
"--pass" parameter is parsed as "--password"
[here](https://github.com/Keeper-Security/Commander/blob/3f7ca720e3f6363f2b160b5659d9f57fb4c02b25/keepercommander/__main__.py#L111) for some reason

As a workaround,
keeper "add --login 'test' --pass 'foo' --url 'http://google/com' 'test'"

**Comment by craiglurey** [comment]
Pushed and updated PyPi
