### ISSUE TITLE
`cd` exits with status "success" when dir does not exist

### ISSUE THREAD

**Issue by elouanKeryell-Even** [Keeper-Security/Commander#215]
**What happened**:

I called command `keeper cd` on a non-existent folder, and it exited with "success" status, i.e. exit code 0.

- Call `keeper cd` on a non-existent folder:

```
$ keeper --user elouan.keryell-even@gisaia.com --password <redacted> cd '/non-existent-dir'
cd: Folder /non-existent-dir not found
```

- Check exit status:

```
$ echo $?
0
```

**What you expected to happen**:

I expected to `keeper` to exit with status "failure", i.e. return code != 0

**How to reproduce it (as minimally and precisely as possible)**:

```bash
# Call command
keeper cd '/non-existent-dir'

# Check exit status
echo $?
```

**Environment**:
- `keepercommander` version:

```
$ pip3 show keepercommander | grep Version:
Version: 4.26
```

- OS (e.g: `cat /etc/os-release`):

```
$ (source /etc/*-release && echo "$DISTRIB_DESCRIPTION")
Ubuntu 19.10
```

- Kernel (e.g. `uname -a`):

```
$ uname -a
Linux baume 5.3.0-29-generic #31-Ubuntu SMP Fri Jan 17 17:27:26 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by sk-keeper** [comment]
this issue is fixed in 4.29
