### ISSUE TITLE
`ls` exits with status "success" when record/folder does not exist

### ISSUE THREAD

**Issue by elouanKeryell-Even** [Keeper-Security/Commander#217]
**What happened**:

I called command `keeper ls` on a non-existent folder, and it exited with a "success" status (i.e. return code != 0).

- Call `keeper ls` on a non-existent folder:

```
$ keeper --user elouan.keryell-even@gisaia.com --password <redacted> ls '/non-existent/plop'
ls: non-existent/plop: No such folder or record
```

- Check return code:

```
$ echo $?
0
```

**What you expected to happen**:

I expected command to fail, i.e. to return a code != 0.

**How to reproduce it (as minimally and precisely as possible)**:

```bash
# Call command
keeper ls /non-existent

# Check return code
echo $?
```

**Environment**:
- `keepercommander` version:

```
$ pip3 show keepercommander | grep Version:
Version: 4.26
```

- OS (e.g: `cat /etc/os-release`):

```
$ (source /etc/*-release && echo "$DISTRIB_DESCRIPTION")
Ubuntu 19.10
```

**Comment by sk-keeper** [comment]
this issue is fixed in 4.29
