### ISSUE TITLE
Renaming attachment on record creation does not fully work

### ISSUE THREAD

**Issue by elouanKeryell-Even** [Keeper-Security/Commander#219]
**What happened**:

While creating a record, I attached file `abcd.txt` to it:

![image](https://user-images.githubusercontent.com/9483289/74665469-152b5500-51a0-11ea-88f2-ecdcba73b775.png)

---

Still in the "record creation" interface, I changed the name of the attached file to `defg.txt`:

![image](https://user-images.githubusercontent.com/9483289/74665528-39873180-51a0-11ea-8d04-dc73fbc07e55.png)

---

Then, I submitted the form, and the record got correctly created.

![image](https://user-images.githubusercontent.com/9483289/74665867-c4682c00-51a0-11ea-8e48-676bbe998251.png)

---

However, when I try downloading back the attached file, it is still called with the old name, i.e. `abcd.txt`:

![image](https://user-images.githubusercontent.com/9483289/74665812-ac90a800-51a0-11ea-97f3-713bea3dc89d.png)

---

**What you expected to happen**:

I expected the downloaded file to be named after what I typed in the "record creation" form.

**Comment by sk-keeper** [comment]
To be fixed in the next Commander release

**Comment by sk-keeper** [comment]
this issue is fixed in 4.29
