### ISSUE TITLE
No error on incorrect `--custom` format on `add` command

### ISSUE THREAD

**Issue by elouanKeryell-Even** [Keeper-Security/Commander#221]
**What happened**:

I created a record with a custom field using command `keeper add`:

```
$ keeper --user elouan.keryell-even@gisaia.com --password '<redacted>' add --custom 'key=value' --force test-record
$
```

I used an incorrect format for flag `--custom` (`key=value` instead of `key: value`), so the record was created empty:

---

![image](https://user-images.githubusercontent.com/9483289/74741608-6baa9900-525d-11ea-8baa-09eeb10211f4.png)

---

What bothers me is that the command did not raise any error message, and it returned a success exit code:

```
$ echo $?
0
$
```

**What you expected to happen**:

I expected:

- an error message, maybe something like ``Wrong format for flag `--custom` ``, or maybe a python exception stack trace
- an "error" exit code (i.e. not 0)

**Anything else we need to know?**:

**Environment**:

- `keepercommander` version:

```
$ pip3 show keepercommander | grep Version:
Version: 4.28
```

**Comment by sk-keeper** [comment]
this issue is fixed in 4.29
