### ISSUE TITLE
Dotnet Keeper sdk - possible bug in retrieving vault records

### ISSUE THREAD

**Issue by mxiong-PTI** [Keeper-Security/Commander#231]
When retrieving the keeper records using the dotnet sdk and running the code it seems to produce no records in the vault. However when debugging and stepping through each line of code manually the vault will pull back the records. 

I do use a few Out-Null's just so the line of code doesn't write any response to the terminal since I don't need them.

Here's a sample code written in powershell.

	$storage = New-Object KeeperSecurity.Sdk.JsonConfigurationStorage
	$Auth = New-Object KeeperSecurity.Sdk.AuthContext($storage, $null)

	#Initialize user configuration and set the login credentials.
	$keeperLogin = New-Object KeeperSecurity.Sdk.UserConfiguration
	$keeperLogin.Username = 'KeeperUsername'
	$keeperLogin.Password = 'KeeperPassword'

	#Login to keeper
	$Auth.Login($keeperLogin) | Out-Null

	#Access the vault and sync down the data from the vault
	$vault = [KeeperSecurity.Sdk.Vault]::new($Auth)
	[KeeperSecurity.Sdk.SyncDownExtension]::SyncDown($vault) | Out-Null

	#Search through each record and look for a specific phrase. 
	$records = $vault.Records 

$vault and $records in this case comes back null if I run the code but if I debug it and step through, they will populate with the records. 
Please advise.

Thank you,
Ma Xiong

**Comment by sk-keeper** [comment]
Try adding .GetAwaiter().GetResult() after SyncDown($vault)

If it is OK when you debug then SyncDown is not awaited
In C# it would be 
await SyncDownExtensions.SyncDown(vault);
in PowerShell 
[KeeperSecurity.Sdk.SyncDownExtension]::SyncDown($vault).GetAwaiter().GetResult() | Out-Null

**Comment by mxiong-PTI** [comment]
Thank you! this did the trick!

**Comment by favy87** [comment]
Al final simplificando mucho el codigo he conseguido que funcione algo asi, despues de leer algun caso cerrado

JsonConfigurationStorage storage = new JsonConfigurationStorage();
KeeperEndpoint ke = new KeeperEndpoint(storage);
AuthContext Auth = new AuthContext(ke, null);

//Initialize user configuration and set the login credentials.
UserConfiguration keeperLogin = new UserConfiguration();
keeperLogin.Username = "username";
keeperLogin.Password = "pass";

//Login to keeper
await Auth.Login(keeperLogin);

//Access the vault and sync down the data from the vault
Vault vault = new Vault(Auth);
await SyncDownExtension.SyncDown(vault);

PasswordRecord record = new PasswordRecord();
vault.TryGetRecord("xxxxxxx", out record);
MessageBox.Show( record.Password);

Es mucho mas rapido ejecutar commander en c# que en python.
