### ISSUE TITLE
keeper Login hangs on Windows Git Bash MINGW64

### ISSUE THREAD

**Issue by matteius** [Keeper-Security/Commander#232]
Login hangs on Windows Git Bash MINGW64 -- 
If I don't specify the username, I get the expected prompt saying I am not logged in.
$ keeper login
...      User(Email):
Not logged in>

When I specify the username, it hangs and never prompts for password, hitting Ctrl + C doesn't kill the application and I have to eventually exit out of the shell.  Similar experience in Cygwin.

However I am able to login just fine and use keeper commander from within my Linux VM that is using bash.

**Comment by sk-keeper** [comment]
I assume you use Windows distribution of Python (not Cygwin or MSYS one). Even Python interpreter does not work in this configuration for me. It does not hang, though, Ctrl+C works as expected just console input is broken. 
Can you launch python in your bash session? Is it functional?

**Comment by matteius** [comment]
Yes, I use Python just fine in the same environments, including can use virtualenv.  I am migrating from using a different password manager that has a CLI that also worked.

```$ python
Python 3.7.1 (v3.7.1:260ec2c36a, Oct 20 2018, 14:57:15) [MSC v.1915 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> 2+2 == 4
True
>>> exit()
```

**Comment by sk-keeper** [comment]
**Git Bash MINGW64** 
```
$ python
bash: /c/Users/keeper/AppData/Local/Microsoft/WindowsApps/python: Permission denied
```

**Git Bash, Keeper venv**. No "Permission denied" error. No python prompt. Ctrl+C does not work (it used to work in MSYS2)
```
$ . PY/keeper/Scripts/activate
(keeper)
DESKTOP-BHD0EUO+keeper@DESKTOP-BHD0EUO MINGW64 ~
$ python
```

**cmd.exe** OK
```
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community>python
Python 3.7.7 (tags/v3.7.7:d7c567b08f, Mar 10 2020, 11:52:54) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>
```

**Comment by matteius** [comment]
Seems like a host level permission issue if you are unable to launch python from Git Bash MINGW64 -- it hasn't been a problem on the few windows machines I've run on.

You are definitely correct that it works from within cmd.exe which I hadn't thought to try before, so its nice to know I have that option of using the CLI.  Thanks!
