### ISSUE TITLE
Nuget version? Samples out-of-date?

### ISSUE THREAD

**Issue by simishag** [Keeper-Security/Commander#233]
I'm trying to follow along with the .NET samples provided, but I am having trouble getting them to build as provided. There are a few different versions on Nuget and there are clearly some differences in the interfaces among the versions that are not reflected in the repository here. The last update to this repo appears to be 10 months ago, but the Nuget versions are much more recent. In fact the most recent Nuget release was yesterday (4/21/2020).

Additionally, the Project URL in Nuget is incorrect (returns 404).

**Comment by sk-keeper** [comment]
The library published on Nuget is under development. It does not have stable API. It is not advertised and source repository is not public yet. Yes, nuget version 0.9.5 is broken. It was supposed to be v0.9.5-alpha1. I will fix this issue.
.NET samples are supposed to work fine with the library coming with that samples.

**Comment by sk-keeper** [comment]
The broken package is removed from listing
