### ISSUE TITLE
class Ui : IAuthUI

### ISSUE THREAD

**Issue by favy87** [Keeper-Security/Commander#236]
Hola, creo que los paquetes .DLL que se incluyen no estan actualizados. Estoy intentando crear una clase ui : IAuthUI y me dice que la clase no implementa ciertos miembros.

Adjunto pantallazo para que me entendais.
![error class ui](https://user-images.githubusercontent.com/5238141/81063000-50a00a80-8ed7-11ea-9895-b1a6f8fad1a8.jpg)

**Comment by sk-keeper** [comment]
Aquí hay un enlace a la implementación predeterminada de la interfaz IAuthUI
https://github.com/Keeper-Security/Commander/blob/81567bfb8d7a1d672ccb970ce9c57c81c37b7f76/dotnet-keeper-sdk/Commander/Program.cs#L113
Tiene una aplicación WinForms, por lo que se supone que la implementación del método GetUserCredentials (credenciales IUserCredentials) debe mostrar un formulario con campos de entrada de nombre de usuario y contraseña. El parámetro "credenciales", si no es nulo, puede contener la última información de usuario registrada.

Se supone que el método GetTwoFactorCode muestra un formulario que le pide al usuario que ingrese el código de autorización de Second Factor

**Comment by sk-keeper** [comment]
![loginform](https://user-images.githubusercontent.com/15200397/81212435-c06ecd80-8f89-11ea-817b-13f812b2c604.png)

GetUserCredentials

**Comment by favy87** [comment]
No puedo compilar porque las librerías que te indico a la derecha no tienen esas declaraciones. Puede ser que se hayan incluido después y no se hayan vuelto a compilar para incluir los cambios.

Puede ser?

Obtener Outlook para Android<https://aka.ms/ghei36>

________________________________

**Comment by sk-keeper** [comment]
De hecho, la biblioteca de la derecha declara que los métodos.
https://github.com/Keeper-Security/Commander/blob/81567bfb8d7a1d672ccb970ce9c57c81c37b7f76/dotnet-keeper-sdk/KeeperSdk/Ui.cs#L11
Su código a la izquierda necesita proporcionar implementación para estos métodos. Mostrar formulario de inicio de sesión de nombre de usuario / contraseña para el método "GetUserCredentials"
y formulario de código 2FA para "GetTwoFactorCode"

**Comment by sk-keeper** [comment]
`            private TaskCompletionSource<IUserCredentials> _credentials;
            public Task<IUserCredentials> GetUserCredentials(IUserCredentials credentials)
            {
                // Show Login form
                _credentials = new TaskCompletionSource<IUserCredentials>();
                return _credentials.Task;
            }

            void SubmitLoginForm() { 
                var cred = new UserCredencials
                    {
                        Username = "username",
                        Password = "password"
                    };
                _credentials.SetResult(cred);
            }`

**Comment by favy87** [comment]
Disculpame pero creo qe es algo de los archivos DLL que se incuten compilados.
Tengo el mismo codigo y do librerias diferentes.

Esta libreria no tiene ese metodo implementado y falla en windows form
Commander-master\dotnet-keeper-sdk\KeeperSdk\bin\Debug\net45\KeeperSdk.dll

Esta libreria si que tiene ese metodo implemenado y funciona
Commander-master\dotnet-keeper-sdk\KeeperSdk\obj\Debug\netstandard2.0\KeeperSdk.dll

¿Podeis hacer el ejemplo de Commander con un WindowsForm? Por ejemplo un richtextbox para la consola y un textbox para introducir comandos?

**Comment by sk-keeper** [comment]
Se espera que el proyecto KeeperSdk construya tres DLL para tres objetivos .NET (.NET Framework, .Net Standard y .NET Core). Su proyecto utiliza el objetivo correcto. Puedo ver Debug \ net45 \ KeeperSdk.dll en la esquina inferior derecha de las capturas de pantalla. No creo que haya una aplicación de ejemplo de Commander para WinForms.

**Comment by favy87** [comment]
Al final he simplificado mucho lo que queria y ha funcionado leyendo un caso cerrado de otro usuario y adaptandolo. Commander es mucho mas rapido en c# en responder que en python.

JsonConfigurationStorage storage = new JsonConfigurationStorage();
KeeperEndpoint ke = new KeeperEndpoint(storage);
AuthContext Auth = new AuthContext(ke, null);

//Initialize user configuration and set the login credentials.
UserConfiguration keeperLogin = new UserConfiguration();
keeperLogin.Username = "username";
keeperLogin.Password = "pass";

//Login to keeper
await Auth.Login(keeperLogin);

//Access the vault and sync down the data from the vault
Vault vault = new Vault(Auth);
await SyncDownExtension.SyncDown(vault);

PasswordRecord record = new PasswordRecord();
vault.TryGetRecord("xxxxxxx", out record);
MessageBox.Show( record.Password);

**Comment by sk-keeper** [comment]
This code is going works until the "Login" flow requires some user input. 
For instance, provide 2FA code. 

The following line of code, the `null` part of it
```AuthContext Auth = new AuthContext(ke, null);```
makes "login" flow fail if customer's account requires second factor authentication

I would not do that. I would support at least 2FA flow in the class implementing IAuthUI interface. 
It is `GetTwoFactorCode` method. Any other methods may return default value or throw exception.
The implementation of `GetTwoFactorCode` method is quite simple for the WinForms application:

```
private TaskCompletionSource<string> _secondFactorTask;
public Task<string> GetTwoFactorCode(IUserCredentials credentials)
{
   _secondFactorTask = new TaskCompletionSource<IUserCredentials>();
   //TODO Show "Enter 2FA Code" form
   return _secondFactorTask.Task;
}

// When customer clicks "OK" button on
void Submit2FACodeButtonClicked(string code) { 
  _secondFactorTask.SetResult(code);
}

```

**Comment by sk-keeper** [comment]
<img width="466" alt="Screen Shot 2020-05-06 at 1 58 19 PM" src="https://user-images.githubusercontent.com/15200397/81227742-c1135e00-8fa1-11ea-9d4f-e541398b713f.png">
Here is an example of 2FA form in the Web Vault

**Comment by favy87** [comment]
Existe algo parecido a vault.dispose() ?

Tengo unos 500 registros y consume memoria, pasa de 20MB a 45MB en RAM despues de descargar la informacion. me gustaria una vez obtenido el password del registro que necesito, vaciar la memoria y seguir la ejecucion del prgrama.

**Comment by sk-keeper** [comment]
No, there is not need for Dispose. Just `auth.Logout();` and set `vault=null;`. Memory will be released with the next garbage collector cycle
