### ISSUE TITLE
Releases or tags

### ISSUE THREAD

**Issue by ejiek** [Keeper-Security/Commander#237]
This software is versioned ([pypi has its versions](https://pypi.org/project/keepercommander/#history)).

Can you please add related tags to this repository.
(I don't ask for the old ones, just from now on)

It's very helpful for distribution packagers to have them because the package is usually built from source.
And it's good to have reproducible build process and be sure you are building the exact thing, not the top of master =]

[AUR example](https://aur.archlinux.org/packages/python-keeper-commander-git/) is git based and there is no other option right now =\

Thanks!

**Comment by sk-keeper** [comment]
Thank you for drawing out attention to this issue. We'll start tagging our releases in the Github.
