### ISSUE TITLE
U2F fails in batch mode

### ISSUE THREAD

**Issue by ad8-bdl** [Keeper-Security/Commander#238]
When using batch mode with a 2FA Yubikey enabled account, keeper prompts for the U2F touch however immediately falls through to a 2FA code prompt, as if "Enter" had been pressed.

env: 
```
% sw_vers 
ProductName:	Mac OS X
ProductVersion:	10.15.4
BuildVersion:	19E287
% keeper --version                                         
Keeper Commander, version 4.31
```

- keeper installed via `pip3`, per readme

repro:
```
% rm config.json
% echo 'whoami' | keeper --user 'user@example.com' -
Password:

Touch the flashing U2F device to authenticate or press Enter to resume with the primary two factor authentication...
Two-Factor Code:
```

- same thing when using `--batch-mode shell`
- fwiw, the yubikey begins flashing at the expected time; entering a valid code succeeds

**Comment by ad8-bdl** [comment]
Also, the message "Touch the flashing U2F device to authenticate or press Enter to resume with the primary two factor authentication..." is sent to `stdout`; should be `stderr` as per the "Two-Factor Code" prompt.

**Comment by sk-keeper** [comment]
As far as I can see this issue, when user interaction is required in a batch mode we can either
1. interrupt batch mode and try to interact with user. In this case it's OK to use stdout as long as stdin is going to be used 
2. fail a batch
Commander uses the first approach. It's subjective which way is better.

**Comment by ad8-bdl** [comment]
I'd have expected batch-mode to be intended in programmatic use cases, and thus stdout probably wouldn't be the user's terminal. e.g.  You can't use stdout when you're directing it to a pipe or file. IMHO you should be able to do:
```
echo -e 'sync-down\nexport --format json\nlogout' | keeper --user "${keeperuser}" - | gpg --sign --encrypt --recipient "${keeperuser}" > keeper-$(date '+%Y-%m-%d').json.gpg
```
without the backup including garbage from the authentication process.

**Comment by ad8-bdl** [comment]
The fix for this issue, PR #241 , doesn't appear to have been merged yet. Any idea when this might be done?

**Comment by ad8-bdl** [comment]
The issue is still present with the new 'v3' authentication flow.

Expected behaviour is that running in batch mode should send all auth flow to the console, such that one can run commands like 
`echo 'whoami' | keeper - > file`

**Comment by sk-keeper** [comment]
The only acceptable `login` user interaction while in the batch  mode is asking for password.
So `persistent login` is not the only option though the most convenient.
2fa login step (and any other non-password steps) uses stdin/stdout. It breaks the batch mode.

The `config.json` file could be prepared for password only login if `persistent login` is not an option.

**Comment by ad8-bdl** [comment]
> The only acceptable login user interaction while in the batch mode is asking for password.

Why's that? How is interacting for a password any different than interacting for a password + MFA? Consider a passwordless future - the "interaction" may not even be on the console, it could be via my phone.

Perhaps I should explain my use case better: my goal is to prepare a set of Keeper commands (batch commands) to be executed by a user. For example, a simple wrapper shell script that might look like this

    #!/bin/sh
    
    keeper --batch-mode - <<.
    whoami
    ls
    .


Now, as a workaround I can do

    #!/bin/sh
    
    keeper this-device persistent-login on
    keeper --batch-mode - <<.
    whoami
    ls
    this-device persistent-login off
    .

However the workaround is fragile - if the script or batch commands fail, the persistent-login will not be nuked, and we'll have a nice backdoor hanging around.

**Comment by sk-keeper** [comment]
I'm not sure if it documented but Commander is supposed to suppress command errors if command starts with `@`
For instance:
```
@mkdir "Folder"
```
is not going to fail is the folder exists

**Comment by ad8-bdl** [comment]
> No idea how I missed this when RTFM

_Now_ I see how I missed this in the doc: it's not really made obvious.

There are a couple of issues with this feature, ref. #903
