### ISSUE TITLE
Llamar a autofill desde c#

### ISSUE THREAD

**Issue by favy87** [Keeper-Security/Commander#239]
¿Se puede invocar desde c# la misma funcion que hace el boton "Iniciar" que aparece en la boveda de Keeper?

![boton iniciar](https://user-images.githubusercontent.com/5238141/81387310-c2b26280-9116-11ea-8dfc-1dbce8834aea.jpg)

**Comment by sk-keeper** [comment]
The Web Vault "Launch" button opens Login URL in a new browser tab. It does not log you in.
`System.Diagnostics.Process.Start(record.Link);`
You need to have Browser Extension installed to be assisted with login in the browser window.
C# application can open a browser and provide copy/paste functionality for username and password.
