### ISSUE TITLE
2FA tokens should have a configurable expiry time, or option to not persist on disk

### ISSUE THREAD

**Issue by ad8-bdl** [Keeper-Security/Commander#240]
At present when a user with 2FA enabled authenticates with the `keeper` / commander CLI client, the `mfa_token` is persisted on disk in the `config.json` file. This token appears to be valid indefinitely, or 30 days if the `device_token_expiration` option is set to `true` (presumably this only applies to the token associated with this client rather than all clients?). There is no command line flag that can set `device_token_expiration`.

There should be an option to control the 2FA authentication token persistence, i.e. one or all of:

- a flag to not save the token to disk, and/or
- add a command to forcefully invalidate the current token (or invalidate the token in the existing `logout` command), or
- at least add a command line flag for `device_token_expiration` with a user-defined period. 

An example use case is very occasional, ad-hoc invocation of the `keeper` CLI client - I want to ensure 2FA is required every time the client is used.

**Comment by sk-keeper** [comment]
Yes, it would be nice to be able to specify device token expiration period at the time user enters 2FA code. I am not sure about the best solution for this issue.
1. Additional argument to the `login` command - hard to discover
2. "Magic" character (like dash "-" in front/at the end of 2FA code) is confusing
3. Additional prompt is annoying even if default answer is present.
Commander already has some solution: `device_token_expiration` option.
Maybe we could add a command the lets you modify the configuration file from the Commander itself.

**Comment by sk-keeper** [comment]
I think we can try to use "auto-completion" functionality (Tab) to switch between 2FA token expiration choices

**Comment by ad8-bdl** [comment]
Just nuking the 2FA token when you issue the `logout` command seems to be the simplest, most obvious approach to me. (Indeed, that mimics the web UI - when I explicitly logout I have to re-enact 2FA; I have "require 2FA on every login" set.)

Not sure what you mean re. tab completion; 2FA could be a yubikey without any keyboard interaction.

**Comment by sk-keeper** [comment]
There is not just yubikey 2FA in Keeper. U2F auth is always a "second" 2FA method. Commander is always in input mode.

**Comment by b1tninja** [comment]
I see two things discussed here,

1. The user experience of entering in the MFA/2fa/u2f (and the inherent troubles of python3's and lack of `raw_input()` equivalent, meaning you must resort to threading and trickory).
2. Enhancements for better controlling the device token expiration.

I looked at `device_token_expiration` as you mentioned, the current API can support a granularity of days.
https://github.com/Keeper-Security/Commander/blob/a7ae70ff7807f969858343a353e401e00c555f6e/keepercommander/api.py#L131

I'll see what we can do

**Comment by sk-keeper** [comment]
Fixed. 2fa token expiration is can be changed now.
