### ISSUE TITLE
Authentication retry always fails

### ISSUE THREAD

**Issue by ad8-bdl** [Keeper-Security/Commander#242]
So I fat-finger my password - `keeper` offers me a second go but always returns error/failed even with the correct password.

env:
```
% sw_vers 
ProductName:	Mac OS X
ProductVersion:	10.15.4
BuildVersion:	19E287
% keeper --version                                         
Keeper Commander, version 4.31
```

keeper installed via `pip3`, per readme

repro:

```
% echo 'whoami' | keeper --user "${keeperuser}" -  
Password: 
Authentication failed.
Password: 
AuthenticationError Error: Authentication failed.
```

- enter an incorrect password in response to the first prompt; a correct password to the second

expect:
- keeper should either not offer a second attempt, or accept it if correct

**Comment by sk-keeper** [comment]
Yes, it is a bug. It will be fixed in the next Commander release.
Thank you for reporting it.
