### ISSUE TITLE
`export` fails to include attachments, for at least json format

### ISSUE THREAD

**Issue by ad8-bdl** [Keeper-Security/Commander#243]
The doc for the `export` command notes "exports include all file attachments." This is not the case for at least the json format. `export` should include attachments.

The notes in the "Importing Records into Keeper" and "Exporting Records from Keeper" imply the JSON and CSV file formats include only limited parts of a record - there should be an export format that includes all data.

**Comment by sk-keeper** [comment]
The full quote is "Keepass exports include all file attachments."

**Comment by ad8-bdl** [comment]
I misread the doc ("Keeper" vs "Keepass"!), including that was a red herring.

The issue / feature request is:
> ... there should be an export format that includes all data.
