### ISSUE TITLE
connect on different platforms

### ISSUE THREAD

**Issue by mac2000** [Keeper-Security/Commander#249]
Hello, I'm currently using two platforms (windows and macos) on a daily basis, wondering if there is a way for me to have different connect commands depending on platform (e.g. to start RDP on windows I probably will start mstsc.exe, but on macos it will be totally different story)

**Comment by sk-keeper** [comment]
README.md file contains sample on using `connect` Commander's command with RDP and SSH.
A single record may have many endpoints for the `connect` command.
The `connect` command does not choose/filter out endpoints depending on the platform Commander is running. You have to create two separate endpoints.

**Comment by mac2000** [comment]
Indeed, it should work, so idea here is to manualy handle it by givin different names for connect to work with, e.g. for the same record I might have more than one `connect:xxx` custom fields, e.g. `connect:contoso-windows-msts`, `connect:contoso-macos-rdp`, etc
