### ISSUE TITLE
Zero-knowledge and commander not working on SSH nor RDP

### ISSUE THREAD

**Issue by Mysterehyde** [Keeper-Security/Commander#255]
Hi, 

It seems that we have trouble with the zero-knowledge option, that is quite mandatory for us and commander.
We provisionned (on windows 10) RDP connexions and SSH connexions (with putty) that are perfectly working with a normal account. But we also need to have zero-knowledge accounts that use this hosts, but without knowing the passwords. And it seems to fail.

Did we miss something in profile configuration or is it normal behavior or just a bug maybe? We used the last 3.8.3 Winpython codes (more than one tested) .

Thanks in advance !

**Comment by sk-keeper** [comment]
If I got it correctly, you want to share a Keeper record with some user and don't want that user to see the record content, right?
Keeper Enterprise has an option advising the Keeper clients to hide record passwords.
You can configure a team in the enterprise to "Disable viewing passwords".
Records that are shared with the user through that team inherit this option.
[Teams](https://docs.keeper.io/enterprise-guide/teams)

**Comment by craiglurey** [comment]
Hi @Mysterehyde can you please send me an email craig@keepersecurity.com and we'll set up a time to discuss your specific needs.  I'd like your input on some workflow, etc.

**Comment by Mysterehyde** [comment]
> If I got it correctly, you want to share a Keeper record with some user and don't want that user to see the record content, right?

Yes, exactly. I have admin accounts that manage the records, and we want to have users accounts that simply use the records. But for security purpose, we need the user to not know the passwords that they are using. 

> Keeper Enterprise has an option advising the Keeper clients to hide record passwords.
> You can configure a team in the enterprise to "Disable viewing passwords".
> Records that are shared with the user through that team inherit this option.
> [Teams](https://docs.keeper.io/enterprise-guide/teams)

Yes from my point of view, there is two option that I maybe don't use correctly, one in the "role" that says Hide Password, and one in the team that say "desactivate password visualisation". We checked both for the users.

Our use case is made of 70% web connexion, 20% ssh ans 10% RDP (approx. ;-) ), and it's perfeclty ok on the web use case.

Hi @craiglurey , yeah sure, I will send you few screens capture ;-)

Many thanks to both of you !

**Comment by sk-keeper** [comment]
There is an issue that prevents Commander's connect command to use such records. This issue will be fixed in the next release.

**Comment by Mysterehyde** [comment]
Hi ! 
I was able to test the 4.34 version tonight and my use case work just perfect ! 
Thank you so much for the speed, it was really fast ! ;-)

I kept both option checked and the users can't access the password but well using it with putty and mstsc, (obviously still working on web pages) just perfect !
