### ISSUE TITLE
`keepercommander.importer.lastpass` missing in releases on PyPI

### ISSUE THREAD

**Issue by janjagusch** [Keeper-Security/Commander#256]
**`keepercommander` version:** `4.34`

**Experienced behavior**:

Trying to import a Lastpass export file through the keeper shell results in an unexpected error.

**Steps to reproduce:**

```sh
keeper shell
My Vault> import --format=lastpass ~/Downloads/lastpass_export.csv                                                                                                                                                                           
Processing... please wait.
An unexpected error occurred: No module named 'keepercommander.importer.lastpass'. Toggle debug to print traceback
```

**Diagnosis:**

the `lastpass` package is missing in the `importer` package:

```sh
ls /keepercommander/importer
commands.py  csv  imp_exp.py  importer.py  __init__.py  json  keepass  __pycache__
```

that is because "keepercommander.importer.lastpass" is missing in `packages` in [setup.py](https://github.com/Keeper-Security/Commander/blob/master/setup.py)

**Proposed solution:**

Add "keepercommander.importer.lastpass" to `packages` in setup.py

**Comment by craiglurey** [comment]
For now please use the Keeper Desktop application at https://keepersecurity.com/download and use the LastPass import feature in the user interface.  It is more up to date.  We will also check this package in Commander.
