### ISSUE TITLE
Automatic windows hello causes distirbance.

### ISSUE THREAD

**Issue by Rustenberg** [Keeper-Security/Commander#258]
When keeper app locks automatically, Windows hello turns on. If you are watching a video or doing something in a browser, this causes disturbance as cameras and lights turn on. 
Please disable automatic windows hello, as it not automatic anyway, because you need to press the OK button to log in once the cameras recognize you.

**Comment by Rustenberg** [comment]
Sorry if this not the correct place for a windows store app, but that is the closest thing I could find.

**Comment by sk-keeper** [comment]
This issues is filed to the bug tracking system.
Thank you for reporting it.
