### ISSUE TITLE
Sample from /custom folder fails

### ISSUE THREAD

**Issue by jzoran05** [Keeper-Security/Commander#260]
**Environment:**
- MacOS
- VSCode

**Steps to reproduce:**

- Installed keepcommander as described in the instructions from the readme.md (https://github.com/Keeper-Security/Commander#python-installation---linux-and-mac)
- Copied sample code in a .py file
- Run python file with the sample

**Error:**
    from keepercommander.record import Record
ImportError: No module named keepercommander.record

**Comment by sk-keeper** [comment]
You can also check https://github.com/Keeper-Security/Commander/tree/master/tests folder.
It contains integration tests for Commander.
This error means you did not install keepercommander pip package.
If you want to run Keeper Commander from the sources then copy your script to to the root of the Commander repository.
