### ISSUE TITLE
allow option to not cut off table formatting at 32 characters

### ISSUE THREAD

**Issue by josephharding** [Keeper-Security/Commander#303]
In display.py's `formatted_records` function the record title is cut off after 32 characters - we have long record names and have modified this code to allow for up to 64 characters before appending ellipsis. It would be nice if we could pass in some kind of option to return the full record name.

Thanks

**Comment by maksimu** [comment]
What would be a use case to name records with longer than 32 characters? Maybe it should be placed into the folder and then sub-folder instead?

**Comment by josephharding** [comment]
Limiting to 32 characters is fine, but I'd suggest the CLI should only enforce that limit if the GUI also enforces it.

You can imagine a scenario where one team creates records with the web GUI, and another consumes them via the CLI.

The decision to truncate records seems arbitrary and has forced us to fork the repo just to override that limit.

Thanks for your consideration

**Comment by maksimu** [comment]
we will be releasing new version 4.58 that will have the ability to print long titles and url by adding `-v` flag to the following commands `ls`, `list`, and `search`
