### ISSUE TITLE
Keepass export fails on Windows with Python 3.9

### ISSUE THREAD

**Issue by afloresaxs** [Keeper-Security/Commander#308]
When using the Keepass export command the following error appears: 

![image](https://user-images.githubusercontent.com/74670785/99554955-63ff5880-2985-11eb-960f-ab861d724506.png)

![image](https://user-images.githubusercontent.com/74670785/99555457-fa337e80-2985-11eb-8e83-bd9e4fd3a109.png)

I have installed the latest lxml library that the Keepass library needs in order to run properly but it keeps giving me this error and I really need to export my records to a Keepass file.

Down here is the traceback:

`Traceback (most recent call last):
  File "c:\users\defaultuser\appdata\local\programs\python\python39\lib\site-packages\keepercommander\cli.py", line 442, in loop
    result = do_command(params, command)
  File "c:\users\defaultuser\appdata\local\programs\python\python39\lib\site-packages\keepercommander\cli.py", line 280, in do_command
    result = command.execute_args(params, args, command=orig_cmd)
  File "c:\users\defaultuser\appdata\local\programs\python\python39\lib\site-packages\keepercommander\importer\commands.py", line 114, in execute_args
    Command.execute_args(self, params, args, **kwargs)
  File "c:\users\defaultuser\appdata\local\programs\python\python39\lib\site-packages\keepercommander\commands\base.py", line 212, in execute_args
    return self.execute(params, **d)
  File "c:\users\defaultuser\appdata\local\programs\python\python39\lib\site-packages\keepercommander\importer\commands.py", line 189, in execute
    imp_exp.export(params, export_format, export_name, **extra)
  File "c:\users\defaultuser\appdata\local\programs\python\python39\lib\site-packages\keepercommander\importer\imp_exp.py", line 182, in export
    exporter.execute(filename, to_export)
  File "c:\users\defaultuser\appdata\local\programs\python\python39\lib\site-packages\keepercommander\importer\importer.py", line 211, in execute
    self.do_export(filename, records)
  File "c:\users\defaultuser\appdata\local\programs\python\python39\lib\site-packages\keepercommander\importer\keepass\keepass.py", line 304, in do_export
    sub_node = node.find('Group[Name=\'{0}\']'.format(comp))
  File "src\lxml\etree.pyx", line 1532, in lxml.etree._Element.find
  File "src\lxml\_elementpath.py", line 323, in lxml._elementpath.find
  File "src\lxml\_elementpath.py", line 312, in lxml._elementpath.iterfind
  File "src\lxml\_elementpath.py", line 295, in lxml._elementpath._build_path_iterator
  File "src\lxml\_elementpath.py", line 237, in lxml._elementpath.prepare_predicate
  File "<string>", line None
SyntaxError: invalid predicate
An unexpected error occurred: invalid predicate. Toggle debug to print traceback`

**Comment by maksimu** [comment]
Would it be possible to see versions of all libraries installed by running `pip list` (add `-v` for verbose output). Here is what I see on my side and it executes properly on Windows 10:

```
C:\Users\mtest>pip list -v
Package         Version     Location                                                                   Installer
--------------- ----------- -------------------------------------------------------------------------- ---------
asciitree       0.3.3       c:\users\mtest\appdata\local\programs\python\python39\lib\site-packages
certifi         2020.11.8   c:\users\mtest\appdata\local\programs\python\python39\lib\site-packages pip
cffi            1.14.3      c:\users\mtest\appdata\local\programs\python\python39\lib\site-packages pip
chardet         3.0.4       c:\users\mtest\appdata\local\programs\python\python39\lib\site-packages pip
colorama        0.4.4       c:\users\mtest\appdata\local\programs\python\python39\lib\site-packages pip
cryptography    3.2.1       c:\users\mtest\appdata\local\programs\python\python39\lib\site-packages pip
idna            2.10        c:\users\mtest\appdata\local\programs\python\python39\lib\site-packages pip
keepercommander 4.57        c:\users\mtest\appdata\local\programs\python\python39\lib\site-packages pip
libkeepass      0.3.1.post1 c:\users\mtest\appdata\local\programs\python\python39\lib\site-packages pip
lxml            4.6.1       c:\users\mtest\appdata\local\programs\python\python39\lib\site-packages pip
pip             20.2.3      c:\users\mtest\appdata\local\programs\python\python39\lib\site-packages pip
prompt-toolkit  2.0.10      c:\users\mtest\appdata\local\programs\python\python39\lib\site-packages pip
protobuf        3.14.0      c:\users\mtest\appdata\local\programs\python\python39\lib\site-packages pip
pycparser       2.20        c:\users\mtest\appdata\local\programs\python\python39\lib\site-packages pip
pycryptodome    3.9.9       c:\users\mtest\appdata\local\programs\python\python39\lib\site-packages pip
pycryptodomex   3.9.9       c:\users\mtest\appdata\local\programs\python\python39\lib\site-packages pip
pyperclip       1.8.1       c:\users\mtest\appdata\local\programs\python\python39\lib\site-packages
requests        2.25.0      c:\users\mtest\appdata\local\programs\python\python39\lib\site-packages pip
setuptools      49.2.1      c:\users\mtest\appdata\local\programs\python\python39\lib\site-packages pip
six             1.15.0      c:\users\mtest\appdata\local\programs\python\python39\lib\site-packages pip
tabulate        0.8.7       c:\users\mtest\appdata\local\programs\python\python39\lib\site-packages pip
urllib3         1.26.2      c:\users\mtest\appdata\local\programs\python\python39\lib\site-packages pip
wcwidth         0.2.5       c:\users\mtest\appdata\local\programs\python\python39\lib\site-packages pip
WARNING: You are using pip version 20.2.3; however, version 20.2.4 is available.
You should consider upgrading via the 'c:\users\mtest\appdata\local\programs\python\python39\python.exe -m pip install --upgrade pip' command.
```

**Comment by afloresaxs** [comment]
I just updated all of the pip dependencies to yours and this is what i
have, still doesn't work.

[image: image.png]

Alejandro Flores  | SITI | Axosnet
aflores@axosnet.com | www.axosnet.com
T.+52 (81)1683128


Follow us: Facebook MEX. <https://www.facebook.com/Axosnet/?fref=ts> | Facebook
USA. <https://www.facebook.com/axosnetltdco/?fref=ts> | Linkedin
<https://www.linkedin.com/company/axosnet-ltd-co> |

The information transmitted is intended only for the person or entity to
which it is addressed and may contain confidential and/or privileged
material.  Any review, retransmission, dissemination or other use of, or
taking of any action in reliance upon, this information by persons or
entities other than the intended recipient is prohibited. If you received
this in error, please contact the sender and delete the material from any
computer.

**Comment by afloresaxs** [comment]
I just updated all of my pip dependencies and now it looks like this: 

![image](https://user-images.githubusercontent.com/74670785/99602357-efe5a480-29c6-11eb-9cf5-3eadb5c2ab91.png)

It doesn't work yet.

**Comment by maksimu** [comment]
Looks like we have identified the issue. Do you happen to have any non-alphanumeric characters in the names of your shared groups? `libkeepass` has limitation dealing with non-alphanumeric characters. Try to rename your folders to plain text and see if that will solve your issue.

**Comment by afloresaxs** [comment]
Sorry, i don't understand what you mean with shared groups, could you
please be more specific? Like using images or another way to call those
"shared groups"

Alejandro Flores  | SITI | Axosnet
aflores@axosnet.com | www.axosnet.com
T.+52 (81)1683128


Follow us: Facebook MEX. <https://www.facebook.com/Axosnet/?fref=ts> | Facebook
USA. <https://www.facebook.com/axosnetltdco/?fref=ts> | Linkedin
<https://www.linkedin.com/company/axosnet-ltd-co> |

The information transmitted is intended only for the person or entity to
which it is addressed and may contain confidential and/or privileged
material.  Any review, retransmission, dissemination or other use of, or
taking of any action in reliance upon, this information by persons or
entities other than the intended recipient is prohibited. If you received
this in error, please contact the sender and delete the material from any
computer.

**Comment by maksimu** [comment]
@afloresaxs Have you tried a new build of commander? New build should address your issue. If not then check the names of your folders and records, it will be best to have only letters and numbers in the names.

**Comment by maksimu** [comment]
Issue resolved in one of the last releases. Closing
