### ISSUE TITLE
When running the keeper get-rec command, the returned results are not valid JSON

### ISSUE THREAD

**Issue by saldoukhov** [Keeper-Security/Commander#32]
Further, the first two lines of output are always:
 
Downloading records...
Downloaded & Decrypted [104] Records
 
Example Output
 
xxx ~/git/xxx $ keeper --config=/home/xxx/config.json get-rec --uid 7efLlQOd-ElInlMLZoAyWw
Downloading records...
Downloaded & Decrypted [104] Records
{'secret1': 'root', 'link': '', 'custom': [{'type': 'text', 'name': 'cmdr:Rotation @ 2017-02-02 10:57:54', 'value': 'xxx'}, {'type': 'text', 'name': 'cmdr:rules', 'value': '4,6,3'}, {'type': 'text', 'name': 'cmdr:Rotation @ 2017-02-02 11:01:09', 'value': "xxx"}, {'type': 'text', 'name': 'cmdr:Rotation @ 2017-02-02 11:03:06', 'value': 'xxx'}, {'type': 'text', 'name': 'cmdr:Rotation @ 2017-02-02 11:06:06', 'value': 'xxx'}], 'title': 'BIG-IP Admin-Root - Dev', 'notes': '', 'folder': '', 'secret2': 'xxx'}

**Comment by gervert502** [comment]
Thanks a lot
