### ISSUE TITLE
Keeper cli leading hyphen causes uid lookup to fail

### ISSUE THREAD

**Issue by Mathieu-Robitaille** [Keeper-Security/Commander#346]
Hello!

When using keeper cli if there is a leading hyphen in the UID that is auto generated we're encountering an issue where keeper's get function will fail out.

> keeper g -k2Ugv6....
> the following arguments are required: uid

> keeper g "-k2Ugv6...."
> the following arguments are required: uid

> keeper g '-k2Ugv6....'
> the following arguments are required: uid

as shown above this is true for quoted text as well...

> keeper --version
> Keeper Commander, version 4.68

**Comment by sk-keeper** [comment]
Keeper g — -k2Ugv6...
Separate uid with two hyphens
