### ISSUE TITLE
RFE: Add the ability to manage MFA Tokens

### ISSUE THREAD

**Issue by dkarakas1** [Keeper-Security/Commander#35]
This is a three-part request.

1) Provide two types of MFA Token, Global Read-Write and Global Read-Only
2) Allow Tokens to be valid for longer periods, say 1-year, 3-year, 10-year or Forever
3) The ability to create and delete MFA Tokens from the Web GUI interface as well as set/adjust their validity period

**Comment by dkarakas1** [comment]
I see the latest version of commander allows us to expire tokens.

Note: If you want your device tokens to expire, set "device_token_expiration" to "true". If set, your device token will expire in 30 days.

Does this mean that if set to false, tokens never expire?

**Comment by TUNGVU1988** [comment]
yes

**Comment by craiglurey** [comment]
Yes, by default the token will not expire. Documentation was clarified.  We are making many new updates to Commander over the coming weeks ahead.
