### ISSUE TITLE
Uploading a file to the keeper with python script

### ISSUE THREAD

**Issue by giovannabarbosamg** [Keeper-Security/Commander#351]
hello, i would like to know if there is how to upload a file within a record by the keeper cli in python? I looked for a variable in record.py that told about the file and I didn't find it. I expect a light, because there is no way to climb a giant string on the keeper, thanks
If you can give me an example I would be grateful

**Comment by maksimu** [comment]
Hi @giovannabarbosamg 

You can do so by using `upload-attachment` command.

Here is the example:

```
upload-attachment --file C:\Documents\max\plans.pdf RECORD_UID123
```

**Comment by giovannabarbosamg** [comment]
do I put it in RecordUploadAttachmentCommand as it was in the others (edit, add)?

**Comment by maksimu** [comment]
Yes, the code for `upload-attachment` command is in `RecordUploadAttachmentCommand` class.

**Comment by giovannabarbosamg** [comment]
thank you for helping me, I put the code in the following way:
`record_uid = command.execute(my_params,
                                     record=record,
                                     file='home/giovanna/Documents/file.xml',
                                     folder=shared_folder_uid,
                                     generate=False, force=True)`

but I get the error:
`keepercommander.error.CommandError: ('upload-attachment', 'File "h" does not exists')`

he's getting the first letter, how do I change that?

**Comment by idimov-keeper** [comment]
`file` parameter expects multiple attachments - try using a list:
```
# Add record 
r = Record()
r.title = 'Test Record'
r.login = 'someone@company.com'

if api.add_record(my_params, r):
    print('Added record UID='+r.record_uid)

command = RecordUploadAttachmentCommand()
command.execute(my_params, record=r.record_uid, file=['/home/giovanna/Documents/file.xml'])
```

**Comment by giovannabarbosamg** [comment]
It worked.

But divided my file into 3, is there a specific amount of characters for files coming from python? I would like it to be just a file and that when the script is run, the file will be overlaid (the intention is to be a backup automation). Is there any way?

**Comment by giovannabarbosamg** [comment]
I tried to delete the files before running the script again, that's by name, but because it was divided into 3 with the same name, the files are not deleted. I also tried to do a search for records with the name which was mine (config from jnk) to be able to delete and create another one on top but it also doesn't seem possible. could you help me? the intention is to make a continuous backup and overlap the files instead of collecting several. Thanks

**Comment by idimov-keeper** [comment]
In case of multiple files with the same name - use Attachment ID instead of file name
`delete-attachment` Delete a file attachment from the specified record. Specify Record UID and Filename (or Attachment ID)

**Comment by giovannabarbosamg** [comment]
yes, i see this, but i can't find where the attachment's uid is. can you help me?

**Comment by idimov-keeper** [comment]
Use `file-report` command (without arguments) - it shows both Record UID and File ID

ex.
```
My Vault> file-report                                                                                
  #  Title    Record UID              File ID
---  -------  ----------------------  -----------
  1  TestV2   l8SOk9x6C7htCW-xxxxxxx  xx-PHiErwJg
  2  TestV22  K0_FvQxWbrW-yEXxxxxxxx  xx-PHiErwJg
```

**Comment by giovannabarbosamg** [comment]
I saw that this command is used through the command line. would I get the file uid via python script?

**Comment by idimov-keeper** [comment]
Getting file UIDs from a Record via python:
```
rec = api.get_record(my_params, r.record_uid) or Record()
att = rec.attachments or []
file_uids = [x.get('id') for x in att]
# use file_uids ...
```
