### ISSUE TITLE
how can I get the record creation date

### ISSUE THREAD

**Issue by giovannabarbosamg** [Keeper-Security/Commander#352]
hi, i'm building an automation in python and i would like to know how can i delete the first record_uid that was created. the intention is to make a backup automation, so the oldest backup will be deleted.
So I would like to know how I can get the record creation date, it is not possible to do it via RecordHistoryCommand for returning a NoneType to me.
here is the code that gives me the version, modified by and time modified. but I can't do anything with it because it's nonetype

` hist_record = RecordHistoryCommand()`
`  hist_record.execute(my_params, record=record_uid)`

**Comment by idimov-keeper** [comment]
If you need only the timestamp of current (most recent) version it is already in record_cache
`my_params.record_cache[r.record_uid].get('client_modified_time')`
Only If you need to compare first/oldest versions you need RecordHistoryCommand  - following example covers both:
```
rec = api.get_record(my_params, r.record_uid)
cr = my_params.record_cache[r.record_uid]
ts = cr.get('client_modified_time')
print (ts)
print(datetime.datetime.fromtimestamp(ts/1000))

hist_record = RecordHistoryCommand()
hist_record.execute(my_params, record=r.record_uid)
rh = my_params.record_history[r.record_uid]
hlist = rh[0] if rh and rh[0] else []
times = [x.get('client_modified_time') for x in hlist]
# use timestamps for comparison
```
