### ISSUE TITLE
python script does not work with subfolder

### ISSUE THREAD

**Issue by kate-m22w** [Keeper-Security/Commander#357]
hey, i have produced a script that works as a backup in the script, however it creates the record but does not execute the rest of the script when shared_folder_uid is the uid of a subfolder. what do i do to make it work? I tried to put a "\" to separate the uid from the primary folder of the subfolder but it still doesn't work.

`shared_folder_uid = 'subfolder_uid'`

`#create a new record`

`add_command = RecordAddCommand()`
`new_record_uid = add_command.execute(params,
                                     title=title_record,
                                     folder=shared_folder_uid,
                                     generate=False, force=True)
print("Record uid:" + new_record_uid)`

#counting the records
`rec = api.get_shared_folder(params, shared_folder_uid)`
`att = rec.records`
`list_records_uids = [x.get('record_uid') for x in att]`
`list_times = []`
`list_timerecord = []`
`qtd = len(list_records_uids)`

`for record_uid in list_records_uids:`
   `hist_record = RecordHistoryCommand()`
   `hist_record.execute(params, record=record_uid)`
  ` rh = params.record_history[record_uid]`
  ` hlist = rh[0] if rh and rh[0] else []`
   `times = [x.get('client_modified_time') for x in hlist]`
   `record_time = str(min(times, key=int)) + "-" + record_uid`
   `print(times)`
   `print(record_time)`
   `list_timerecord += record_time.split()` 
   `list_times += str(min(times, key=int)).split() `

`index_list_max = list_times.index(max(list_times, key=int))`
`last_record = list_records_uids[index_list_max]`
`print(last_record)`
       ` upload_command = RecordUploadAttachmentCommand()`
       ` record_uid = upload_command.execute(params,
                                            record=last_record,
                                            file=['/home/usr/Documents/att.txt'],
                                            folder=shared_folder_uid,
                                            generate=False, force=True)`
       ` print("upload attachment")`

the code above takes the records and their creation dates to place the file in the last record created. however the code already crashes on the part of `rec = api.get_shared_folder (params, shared_folder_uid)`
`att = rec.records`

with the error (and command output):

`WARNING: root: Shared folder UID not found.`
     `att = rec.records`
`AttributeError: 'NoneType' object has no attribute 'records'`

**Comment by kate-m22w** [comment]
Interesting. I did the check and really said it’s not. but when i create it i say to be a shared folder. furthermore, since creation doesn't work, i created a shared primary folder and tried to move it to another shared primary folder, but i am prevented with an error that says shared folders cannot be moved to another one.

**Comment by idimov-keeper** [comment]
That's correct behavior, so depending on your use case you can either create multiple top-level shared folders or if you prefer to work with sub-folders i.e. regular folders check FolderListCommand() implementation since these are in folder_cache and don't have internal list or records
