### ISSUE TITLE
Device_id Field Not Created When Setting Up Persistent Login

### ISSUE THREAD

**Issue by Kytech** [Keeper-Security/Commander#359]
## Problem Description

After following the steps outlined in the README to enable persistent login (successfully logging in for the first time and completing approval flow, executing `$ keeper this-device register` followed by `$ keeper this-device persistent_login on`), the `config.json` file contains the `private_key`, `device_token`, and `clone_code` entries, but the `device_id` field was never created.

This appears to cause issues when running commands that rely on this `device_id` field. For example, when running `$ keeper this-device rename "New Name"`, the following error is shown and the device name is never changed:
```
An unexpected error occurred: 'KeeperParams' object has no attribute 'device_token_bytes'. Toggle debug to print traceback
```
When running again with the `--debug` flag, the output changes only slightly:
```
INFO:root:Debug ON
DEBUG:root:Params: <keepercommander.params.KeeperParams object at 0x7fd83f15ab50>
Full Sync response
ERROR:root:An unexpected error occurred: 'KeeperParams' object has no attribute 'device_token_bytes'. Toggle debug to print traceback
```

This same error was also produced when running the `this-device persistent_login on` command, but it did appear to enable persistent login as a confirmation message is displayed before the error output. Also, running `this-device` indicates that persistent login is enabled and running `$ keeper shell` indicates that persistent login was used for the connection. As far as I can tell, the main difference here is that the persistent-login still works even with this error, but renaming the device does not work.

## Keeper Commander/Python/OS Version

Keeper version: 4.79
Python version 3.8.5
OS: Ubuntu Linux 20.04 LTS

**Comment by maksimu** [comment]
Hello @Kytech
Can you confirm that you are accessing the correct config file. Without device_id you won't be able to login to Commander and run shell command.

Try to delete existing config file which will be recreated upon the next login.

You can also start commander shell by specifying you own config file name like so: `keeper shell --config myconfig.json`

**Comment by Kytech** [comment]
I can confirm that it is using the .config file that I was expecting. I am seeing the same behavior whether I explicitly pass the config file as a parameter or not.

Recreating the config happens to generate a new one that also does not contain the `device_id` field, but I can still run `keeper shell` and persistent login continues to work. It does contain a `device_token` and `private_key` as well, even though `device_id` does not exist after registering the device and approving it.

**Comment by maksimu** [comment]
@Kytech
There is no need for `device_id` to exist in the config file. In the new login v3 we only need `device_token`, `private_key`, and `clone_code` is mostly needed for the persistent login.

I have pushed a fix for the commands that were not working properly which should be published later today.

**Comment by Kytech** [comment]
@maksimu sounds great! Thank you for your help.
