### ISSUE TITLE
Error with import function

### ISSUE THREAD

**Issue by rickymulder** [Keeper-Security/Commander#36]
Using Python 3.5.3 with pyenv.  When attempting to utilize the keeper cli invocation:
`keeper import --format json import.json`
I get the error:
"Error: string indices must be integers"

My json file is:
{
"title":"Test Record",
"folder": "LWPC pfx",
"secret1": "",
"secret2": "BadPassword",
"link": "https://someurl",
"notes": "This is a test"
}

I have attempted it as requested in the keeper cli directly as well to no avail:
{
"Title":"Test Record",
"Folder": "LWPC pfx",
"Password": "BadPassword",
"Login URL": "https://someurl",
"Notes": "This is a test"
}

**Comment by craiglurey** [comment]
This issue was a documentation problem on our side.  The JSON file must be formatted similar to the below example:

`
[{
    "title":"Dev Server",
    "folder": "Servers",
    "login": "root",
    "password": "lk4j139sk4j",
    "login_url": "https://myserver.com",
    "notes": "These are some notes.",
    "custom_fields": [{"Security Group":"Private"}]
},
{
    "title":"Prod Server",
    "folder": "Servers",
    "login": "root",
    "password": "kj424094fsdjhfs4jf7h",
    "login_url": "https://myprodserver.com",
    "notes": "These are some notes.",
    "custom_fields": [{"Security Group":"Public","IP Address":"12.45.67.8"}]
}]
`
