### ISSUE TITLE
Replace # within csv output

### ISSUE THREAD

**Issue by clowa** [Keeper-Security/Commander#372]
Hey everybody,
I'm using the commander csv output a lot to process the output within the shell. Unfortunately `powershell` isn't able to correctly import the csv since you are using `#` within the output. Would it be possible to replace `#` with something like `count` ? 

The issue first occured after I tried to import a csv file with `Import-Csv` generated by `keeper share-report --owner --format csv --output C:\someFolder` .
`Import-Csv` tries to import the csv columns as custom powershell objects and I guess powershell doesn't accept `#` as a property name.

Hope you guys can help. If there is a better way to process the output within the shell - let me know!

**Comment by sk-keeper** [comment]
This issue is fixed.
