### ISSUE TITLE
can't extract record with uid starting with - (dash)

### ISSUE THREAD

**Issue by Tichy** [Keeper-Security/Commander#376]
Test case: get a record wit an uid starting with -
For this example I just made up an uid

```
./keeper get --format json -etlysAZ3xjsBDs30JxPSA

./keeper get --format json "-etlysAZ3xjsBDs30JxPSA"

./keeper get --format json '-etlysAZ3xjsBDs30JxPSA'
```

In these examples keeper responds with an error "the following arguments are required: uid"
It seems that the UID is treated ad an optional argument.

As a workaround I made a duplicate of the offending records, thus generating a new UID, but I should be able to use whatever UID keeper generated.

**Comment by craiglurey** [comment]
Hi @Tichy place "--" in front.  For example:
./keeper get --format json -- -etlysAZ3xjsBDs30JxPSA

**Comment by Tichy** [comment]
Thanks @craiglurey for the advice! My fault. I missed this option. Now I updated my scripts.
