### ISSUE TITLE
Documentation Update - "Two-Factor Authentication and Device Token"

### ISSUE THREAD

**Issue by dkarakas1** [Keeper-Security/Commander#38]
Please update the documentation section "Two-Factor Authentication and Device Token" to include guidance on:

1. Default behaviour if "device_token_expiration" is omitted from the config.json file
2. Expiration behavior when "device_token_expiration" is set to "false"
3. Proper method for revoking MFA tokens

**Comment by craiglurey** [comment]
Clarified in the documentation.
