### ISSUE TITLE
`add --generate` output is confusing for new users

### ISSUE THREAD

**Issue by groner** [Keeper-Security/Commander#381]
I made the mistake of thinking the output of `add -g` was the generated password, when it is actually the record uid. This seems like an easy mistake for new users to make.

I can think of a few ways to improve this:
1. label the output; use isatty(3) if script compatibility is needed
2. add options to expose the password by printing or clipboard
3. state that the output is no the generated password in the `add` command description or `-g` help text

**Comment by sk-keeper** [comment]
add command send record UID to stdout.
It cannot be changed.
Commander has clipboard-copy command that can copy record password to either clipboard or stdout

Also, "add" command stores record UID to Commander environment
It can be accessed by ${last_record_uid}
`clipboard-copy ${last_record_uid} --output=stdout`
executed immediately after `add -g` command is going output generated password.
