### ISSUE TITLE
Using keepercommander as module

### ISSUE THREAD

**Issue by goranvrbaski** [Keeper-Security/Commander#39]
Hello,

It's a bit tricky to use a keepercommander as a module in project. It's undocumented  and it's not a "developer friendly". For example if I want to use keepercommander in my project I must define class object with some predefined parameters, or there is better (undocumented) way? 

for example I must define class, to be able to use it in my code:

```
import keepercommander.api as keeper


class AuthData:
    def __init__(self):
        self.auth_verifier = ""
        self.server = "https://keepersecurity.com/api/v2/"
        self.debug = False
        self.mfa_token = "token_from_my_device"
        self.mfa_type = "device_token"
        self.user = "my.email.address@mydomain.com"
        self.password = "mypassword"
        self.revision = "0"

auth = AuthData()

keeper.login(auth)
keeper.sync_down(auth)
for item in keeper.search_records(auth, "test"):
    print(item.title)
```

Can you provide examples for using your module in code? Login, generating password for new entry, deleting, etc?

**Comment by craiglurey** [comment]
Sorry for the delay.  Below is an example which will sync down data, decrypt and then display any records that match "Test".  I'll post a few more examples for creating records.

`
from keepercommander.params import KeeperParams
from keepercommander import display, api

my_params = KeeperParams()
my_params.server = 'https://keepersecurity.com/api/v2/'
my_params.mfa_type = 'device_token'
my_params.user = 'someuser@gmail.com'
my_params.password = 'your_master_pass'
my_params.debug = False

api.sync_down(my_params)

results = api.search_records(my_params, 'Test')
display.formatted_records(results)
`

**Comment by goranvrbaski** [comment]
Thank you. It’ll be nice if there is documentation for using this module in code. :)

**Comment by craiglurey** [comment]
Absolutely.  Open to your ideas.  We'll be improving this and adding more examples.

**Comment by craiglurey** [comment]
I added a few examples in the [custom](https://github.com/Keeper-Security/Commander/tree/master/keepercommander/custom) folder which demonstrate a few commands.
