### ISSUE TITLE
Exporting record owner information

### ISSUE THREAD

**Issue by mile-misan-devtech** [Keeper-Security/Commander#40]
Hello,

I cannot find a way to export or get record owner info.
Tried with keeper get and keeper export commands.

Am I missing something or this is not supported?

**Comment by craiglurey** [comment]
Hi, the shared folder commands provide user owner info but not the individual record sharing info yet.  We can definitely add it.  I'll put it on our todo list.

**Comment by ajharahmed** [comment]
Hi please fix this app

**Comment by craiglurey** [comment]
This is now done.  See the "get" command and other shared folder commands.
