### ISSUE TITLE
invalid client version, after upgrade to 16.1.0

### ISSUE THREAD

**Issue by miikkajo** [Keeper-Security/Commander#410]
on linux:

with enterprise account in keepersecurity.eu

pip install keepercommander==4.88
$ keeper login 
works as expected

pip install keepercommander --upgrade
Successfully installed keepercommander-16.1.0

$ keeper login

Error code: client_version
Communication Error: 
invalid client version: Online 15.16.1
Not logged in>

also with personal account:

$ keeper login
...      User(Email): xxxxxx

Error code: client_version
Communication Error: Please update your Keeper app to the latest version from the App Store or from KeeperSecurity.com.  If you are using a web browser, please reload the page or clear your browser cache.
Not logged in>

**Comment by maksimu** [comment]
@miikkajo Thank you very much for reporting this issue. We have fixed this issue and released new Commander version 16.1.1
