### ISSUE TITLE
version mismatch asks for upgrade

### ISSUE THREAD

**Issue by razvan-moj** [Keeper-Security/Commander#43]
When running commander from pip (current release 0.7.10 published yesterday) against keepersecurity.com I get a version mismatch error asking for a client upgrade, while there obviously isn't one. I had to ```pip3 install keepercommander==0.7.9```

**Comment by arlenyan** [comment]
There was a 0.7.10 build released yesterday. Using that version should fix the error you're encountering.

**Comment by razvan-moj** [comment]
Works now, thank you!
