### ISSUE TITLE
Cant login to commander

### ISSUE THREAD

**Issue by KoalaWSMTW** [Keeper-Security/Commander#460]
hi, i try to connect to commander for the first time and i have this error :+1: 
 > keeper login
...      User(Email): *******@****.fr
Please update your Keeper app to the latest version from the App Store or from KeeperSecurity.com.  If you are using a web browser, please reload the page or clear your browser cache.
Not logged in> version
Commander Version: 16.1.7
Not logged in> 

i think i have the latest version.

I try to connect to https://keepersecurity.eu server

**Comment by maksimu** [comment]
Hello @KoalaWSMTW 
We are trying to resolve this issue right now, but in the mean time you can just downgrade your commander and everything should works as expected. Use following command to downgrade:

`pip3 install --upgrade keepercommander==16.1.6`

**Comment by maksimu** [comment]
@KoalaWSMTW we have released new version of Commander 16.1.8 with the fix.
