### ISSUE TITLE
--node option not limiting results in ei with -u, -t or -r arguments

### ISSUE THREAD

**Issue by carlosduplar** [Keeper-Security/Commander#488]
Following #482 , Commander stopped breaking with `ei --node="nodename"` commands. 

Command is not behaving properly, though: --node="nodename" is not filtering results when used with `-u`, `-t` or `-r` arguments. `-n` is currently the only argument correctly filtered by --node.

**Comment by sk-keeper** [comment]
This issue will be fixed in the next Commander release.
