### ISSUE TITLE
Installation Documentation Does Not Work on CentOS 7

### ISSUE THREAD

**Issue by slarti-b** [Keeper-Security/Commander#516]
I installed on Linux.  Followed instructions at https://docs.keeper.io/secrets-manager/commander-cli/commander-installation-setup/installation-on-linux  I was on a CentOS 7 machine so used yum version.  Instructions are effectively
```
yum install -y python3
pip3 --version
pip3 install keepercommander
pip3 install --upgrade keepercommander
```

For me, the `pip3 install keepercommander` failed on a bunch of dependencies.  Tried installing them and it failed on another.  Then I realised that the pip version that CentOS had installed via yum was quite old.  Upgrading that worked.  I did it on another machine, and update it first and it worked first time.  Thus, I believe the instructions should be
```
yum install -y python3
pip3 install --upgrade pip
pip3 install keepercommander
pip3 install --upgrade keepercommander
```
(I did actually run the `pip3 --version` - actually twice, once before and after the `pip3 install --upgrade pip` - but when writing this realised that the `pip3 install --upgrade pip` should also count as checking it's installed (the given rational for `pip3 --version` ) so I don't think the  `pip3 --version` is needed)

**Comment by ladams-keeper** [comment]
Thank you for this feedback, our documentation has been updated
