### ISSUE TITLE
Option to output only password

### ISSUE THREAD

**Issue by slarti-b** [Keeper-Security/Commander#517]
I'm using keeper commander from some scripts to fetch passwords for my CI system.  However, the `find-password` command outputs extra info around the password.

What I'd like to do is (simplified version without error handling)
```bash
PASSWORD=$(keeper --config "$KEEPER_CONFIG" find-password  "$RECORD_NAME" 2>/dev/null)
```
However, I then end up with two lines in the variable.  If my password is "foo" and I echo it out it gives me
```bash
$ echo "$PASSWORD"
> find-password  -- 'Record Bar'
foo
```
when I want just 
```bash
$ echo "$PASSWORD"
foo
```

I can work round it with
```bash
PASSWORD=$(keeper --config "$KEEPER_CONFIG" find-password  "$RECORD_NAME"  | sed -n '/^> find-password  --/!p' 2>/dev/null)
```
but it feels hacky.

If you want to keep the existing functionality could you add a command line switch (say `--raw`) that only outputs the actual value of the password (to stdout anyway - no problem with the rest coming to stderr) ?  Then I could just
```bash
PASSWORD=$(keeper --raw --config "$KEEPER_CONFIG" find-password  "$RECORD_NAME" 2>/dev/null)
```

My current hack feels vulnerable, if the info string changes in the future.  Since the CLI is, presumably, designed at least in part for scripting in this way - and what I need to use in my script is just the password - I think it should support just getting the value.  

Or have I missed an existing switch?  The `--batch-mode` doesn't seem to behave differently in this regard and I couldn't see anything else potentially relevant in the docs.

**Comment by sk-keeper** [comment]
Yes, you are right. 
`> find-password  -- 'Record Bar'` should not be in the default command output.
The fix is merged into the repository and will be included into the next Commander release

**Comment by slarti-b** [comment]
Thanks @sk-keeper!  I couldn't see a commit linked here but think I found the commit - am I right in that it will only apply if I run in `--batch-mode`?

Should I close this issue now, or will it close automatically?

**Comment by sk-keeper** [comment]
The fix is released yesterday. I'll close this issue. Thanks for reporting it.
