### ISSUE TITLE
How  to List records from specific folder  in python script using api from Commander

### ISSUE THREAD

**Issue by Free-devloper** [Keeper-Security/Commander#547]
Hey! I've been working with keeper commander and struggling with a situation where i need to list records using keeper commander api from the commander sdk and I need to list records from the specific folder only I tried to pass the current_folder perimeter with the params but all in vain it retrieves records from every folder in the vault ...

**Comment by kihneman** [comment]
Have you tried `ls <folder_name>`?

**Comment by sk-keeper** [comment]
params  has subfolder_record_cache member that holds record uids per folder
https://github.com/Keeper-Security/Commander/blob/1f703f9bb8e9d24159c121b05d62f50d65d55b07/keepercommander/params.py#L90
Dict[forder_uid, Set[record_uid]]

api.get_record(params, record_uid) loads the record.
https://github.com/Keeper-Security/Commander/blob/1f703f9bb8e9d24159c121b05d62f50d65d55b07/keepercommander/api.py#L1066

https://github.com/Keeper-Security/Commander/blob/1f703f9bb8e9d24159c121b05d62f50d65d55b07/keepercommander/subfolder.py#L82
this method may help you with getting folder_uid from the folder path


resolved = subfolder.try_resolve_path(params, path).   
if not resolved:
  return
folder, file_component = resolved
if file_component
  print('The path cannot be resolved to folder')
  return

records = params.subfolder_record_cache.get(folder.uid)
if records:
  for record_uid in records:
    api.get_record(params, record_uid)

**Comment by Free-devloper** [comment]
Thanks for previous Help I've another question related to that how can i unlink a record from destination folder ..or how can i delete a record from specific folder instead of whole i need to delete the record from a specfific folder which is linked to other folder too but i want to keep one record and delete the record which is placed in destination folder. ps. record_uid of records are same

**Comment by sk-keeper** [comment]
here is the `rm` command code 
https://github.com/Keeper-Security/Commander/blob/581b738d6a087598535f6829f7b33a7e30ff8704/keepercommander/commands/record.py#L538

**Comment by Free-devloper** [comment]
> The most simple way to delete/unlink a record reference is
> 
> from keepercommander import cli cli.do_command('rm --force "path to record"')
> 
> to delete all record references cli.do_command('rm --force --purge -- "record uid"')

What should be the path to record like "Myvalue/folder/recorduid"??

**Comment by sk-keeper** [comment]
You can use record uid instead of record title .
rm "/FolderName/RecordTitle"
and
rm "/FolderName/<RecordUID>"
Both commands remove the same record

**Comment by sk-keeper** [comment]
--purge option forces `rm` command to delete the record from your vault
`rm &lt;Record UID&gt;` with not folder specified unlinks the first found record link. Most likely the record in the root.
`rm &lt;folder_path/Record UID&gt; unlinks the record from the "folder_path"

**Comment by Free-devloper** [comment]
No I didn't used purge command

**Comment by sk-keeper** [comment]
Do you use just record uid?
`rm <Record UID>`
or record UID with the folder path?
`rm <folder_path>/<Record UID>`?

**Comment by Free-devloper** [comment]
I did with folder path

**Comment by sk-keeper** [comment]
Tes, that is correct. `rm` command ignores folder path if record is identified by record uid. That needs to be fixed.
Record needs to be identified by its `title` to be deleted from the particular folder.
record = api.get_record(params, record_uid)
record.title

**Comment by Free-devloper** [comment]
Here is another problem for me..that every record has same title I can't
change that that's requirement.. I want to delete it by reference if that's
somehow possible
