### ISSUE TITLE
Commander is not proxy aware

### ISSUE THREAD

**Issue by Maxiturne** [Keeper-Security/Commander#607]
The application doesnt't seem to be proxy aware : 
Getting "errno 11001 getaddrinfo failed" error while trying to authenticate. In our company we are using an explicit proxy defined in the Windows/Linux/Mac settings.

A check of the proxy configuration on the OS level via the command urllib.request.getproxies() and the usage of ProxyManager if proxy is detected would be a nice add-on to this project.

Thanks in advance,

Maxime

**Comment by sk-keeper** [comment]
Thank you for the feedback. This feature is scheduled for release.

**Comment by sk-keeper** [comment]
HTTP/SOCKS proxy support has been added to the Commander v16.4.7
https://docs.keeper.io/secrets-manager/commander-cli/using-commander/logging-in#logging-in-with-a-proxy
