### ISSUE TITLE
keeper api changed from keepercommander pip

### ISSUE THREAD

**Issue by flybyray** [Keeper-Security/Commander#639]
At least since Friday, January 7, 2022 the api changed and backup exports do not work as expected.

The followingcommand was working without issues with keepercommander 16.3.3 before the date:
```shell
keeper --server "keepersecurity.eu" --user "user@example.com" --password '****' --config "keepersecurity-user.json" --batch-mode export --format keepass "keepersecurity-user" --keepass-file-password '****'
```

Now there appears a new question:

```text
Export to keepass does not support typed records

Do you want to continue? [y/n]:
```

It would be great if there are internal defaults so that this question is not showing up.
Or at least some migration hint how to update config json so that this questions is skip with yes answer.

i already tried updating keepercommander to 16.4.9 but the issue is the same.

**Comment by sk-keeper** [comment]
Issue is fixed
