### ISSUE TITLE
Keeper import failed if attach_cnt is equalt to zero

### ISSUE THREAD

**Issue by OshTival** [Keeper-Security/Commander#642]
![image](https://user-images.githubusercontent.com/79908087/149666485-d87ddb30-153e-407f-a562-6308da060047.png)

https://github.com/Keeper-Security/Commander/blob/2ede4feddf47f1fbdbc230b9d3c1e4e10ebb219b/keepercommander/importer/lastpass/vault.py#L116

**Comment by sk-keeper** [comment]
Do you pass `--file-cache` option to `import` command?

It seems this issue is not related to the value of `attach_cnt` variable.

**Comment by OshTival** [comment]
No, I used 16.4.9.
I already mentioned in your Slack a critical bug in the new version.
![image](https://user-images.githubusercontent.com/79908087/149892169-9fb1a311-1f41-4694-94a8-6548a29c0be7.png)

**Comment by sk-keeper** [comment]
What version `pip show protobuf` you have installed?

**Comment by sk-keeper** [comment]
Commander 16.4.9 import from LastPass issue:
`import --format=lastpass <lastpass email>` completes successfully in Commander 16.4.9 running on MacOS 
`Processing 0 LastPass attachments:
folder          success         8
legacy record   success         14
record          success         23
37 records imported successfully
`
It seems that this line
https://github.com/Keeper-Security/Commander/blob/71d4bf553b5a5d73e1ca7cce8b926cfa8a8d3f16/keepercommander/importer/lastpass/vault.py#L108
failed to return a valid temporary directory.

What OS you are running? Ubuntu?

**Comment by OshTival** [comment]
Ubuntu 20.04.3 LTS

**Comment by sk-keeper** [comment]
There was a bug  as you described. It was fixed in 16.4.9
