### ISSUE TITLE
Yubikey not functioning after upgrade

### ISSUE THREAD

**Issue by chall8908** [Keeper-Security/Commander#681]
I wish I still remembered the last working version, but, unfortunately, I do not.  In the current version of Keeper Commander (16.5.7 for me) WebAuthN does not accept my Yubikey.  A previous version of Keeper Commander _did_ accept this key.

Currently, when I try to use my Yubikey, I get the prompt to touch it which immediately closes and goes back to the menu when I do so.

I've been unable to glean any additional information out of Commander.  No error messages are displayed and none of the debug options seem to do anything.

**Comment by sk-keeper** [comment]
This issue is fixed in the latest Commander release 16.5.8
```Keeper Security stopped supporting U2F security keys starting February 2022.
If you registered your security key prior to this date please re-register it within the Web Vault.
For information on using security keys with Keeper see the documentation: 
https://docs.keeper.io/enterprise-guide/two-factor-authentication#security-keys-fido-webauthn
Commander will use the fallback security key authentication method.
To use your Yubikey with Commander, please touch the flashing Security key one more time.```

The old keys are still supported but you have tap key twice.
