### ISSUE TITLE
error argument: ... expected one argument when '-' is the first character of an id

### ISSUE THREAD

**Issue by flybyray** [Keeper-Security/Commander#713]
Is there documentation how keeper shell expects ids to be escaped when a minus is the first character of that id?

```
Executing [add --login 'XXX' --pass 'YYY' --folder '-withMinuxAsPrefix' -f -t 'TITLE']
argument --folder: expected one argument
```

**Comment by flybyray** [comment]
@sk-keeper 

This is fix or workarround.
But it should be documented here [add-command-record-types](https://docs.keeper.io/secrets-manager/commander-cli/using-commander/command-reference/record-commands#add-command-record-types).

Essentially it is more safe to use arguments with [equals operator](https://stackoverflow.com/a/16175115)

```shell
add --login 'XXX' --pass 'YYY' --folder='-withMinuxAsPrefix' -f -t 'TITLE'
```

PS: Documentation is build from GitBook is there a public repository for that documentation?

**Comment by flybyray** [comment]
@maksimu thx yes. found it too when running `keeper secrets-manager` without arguments

```
  -----
  Note: If the UID you are using contains a dash (-) in the beginning, the value should be wrapped 
  in quotes and prepended with an equal sign. For example:
  secrets-manager share add --app="-fwZjKGbKnZCo1Fh8gsf5w" --secret="-FcesCt6YXcJzpHWWRgoDA"
```

maybe a troubleshoot section should contain a typical sample error `expected one argument` or something similar so that search indexer find it when users search for fixes for that error message.

**Comment by maksimu** [comment]
Thank you for the suggestion! We will discuss this with the team.

**Comment by flybyray** [comment]
@maksimu regarding documentation is there a public repository for documentation to request changes?

https://docs.keeper.io/secrets-manager/commander-cli/using-commander/command-reference/secrets-manager-commands#view-the-details-of-an-individual-application

wrong syntax
```
My Vault> secrets-manager app get --app MyApp                                                                                                                                                                                                                                                                                                                      
Application name is required.
  Example: secrets-manager get app MyApp

```

correct
```
My Vault> secrets-manager app get  MyApp                                                                                                                                                                                                                                                                                                                           

```

**Comment by maksimu** [comment]
Good catch! I've fixed it. As I know there is not public repo for the docs.
