### ISSUE TITLE
client tools should handle throttling independant(on its own)

### ISSUE THREAD

**Issue by flybyray** [Keeper-Security/Commander#714]
Client tools should handle throttling independant(on its own)

Currently users need to play with a delay option ( check out what works for you? ).

Please introduce blocking server calls or handle it transparently in the keeper client code and remove this option!

a run-batch with `-d 1` or `-d 3` produces this after several requests.

```
Executing [add --login ... ]...
Communication Error: throttled
```

If this somehow related to the subscription level. maybe provide a calculation tool which option should work.

**Comment by sk-keeper** [comment]
Keeper will check if there is an easy and safe way to implement recovery from the throttling errors.
It seems that your code creates a lot of records, right? 
It would be much more efficient to add new records using `import` Commander's command.

**Comment by flybyray** [comment]
> It seems that your code creates a lot of records, right? 

Yes. I would normally like to create them directly via keeper plugin in ansible. But there is no create support at the moment. So i have templated a batch file and run it.

> It would be much more efficient to add new records using `import` Commander's command.
Is there a recommended templating input available ( json / yaml ) ?

**Comment by sk-keeper** [comment]
Json is preferred external format.
https://docs.keeper.io/secrets-manager/commander-cli/using-commander/command-reference/import-and-export-commands#detailed-instructions

`export --format=json filename` would export the vault to json file. Exclude `uid` field when import file is created.
The general or legacy Keeper records are pretty simple. The newer record types is more complex and not documented well. `export` command would reveal the typed record fields.

**Comment by sk-keeper** [comment]
Commander v16.6.9 handles `throttled` errors, The command is repeated  after 10 seconds delay.
