### ISSUE TITLE
download-membership command documentation: wrong syntax

### ISSUE THREAD

**Issue by carlosduplar** [Keeper-Security/Commander#717]
Hi,

https://docs.keeper.io/secrets-manager/commander-cli/using-commander/command-reference/import-and-export-commands#unload-membership-command contains the wrong command syntax:

> Command: unload-membership 

should be:

> Command: **download**-membership 

There's also no reference to download-membership in Commander's list of commands when **keeper shell -h** is run.

**Comment by ladams-keeper** [comment]
Thank you for your feedback, we have corrected the documentation.
