### ISSUE TITLE
Record ID not returned when record added

### ISSUE THREAD

**Issue by jonabend-uptake** [Keeper-Security/Commander#728]
v16.6.1

When calling keeper from script
`keeper --user "myemail@company.com" --password "secretstring" add -custom "test1: value1" --folder "folder/subfolder" --title "test123"`

No Record ID is returned.

A Record ID is returned when using `keeper shell`

**Comment by sk-keeper** [comment]
Thank you for the feedback. 
Yes, you are right. The Commander uses logger.info to report command output. It should use `print` instead.
Will be fixed in the next release.

**Comment by sk-keeper** [comment]
the fix is released
