### ISSUE TITLE
What is version 3 mean?

### ISSUE THREAD

**Issue by songponlekpetch** [Keeper-Security/Commander#746]
I ran rotate ssh plugin by creating sshkey record and I see this message. What is version 3 mean?

<img width="876" alt="image" src="https://user-images.githubusercontent.com/8089883/171081280-e01fb505-4f62-4549-82b6-454a53f6d17e.png">

**Comment by ladams-keeper** [comment]
Hi, 
Version 3 records are records with a type.  

If you do a `list` command in Commander, any record with something in the "Type" column is version 3
![image](https://user-images.githubusercontent.com/86691491/172914886-15ad220d-b778-4a26-8a50-5f3138f18774.png)

Currently rotation only works with untyped records (we're updating this soon).

You can create an untyped record in Commander with the `add` command.  Supply the `-v2` flag to generate an untyped record. 
That looks like: `add -v2 --title <TITLE> --login <LOGIN> --url <URL> --pass <PASSWORD>`
