### ISSUE TITLE
Unable to log into with okta sso 

### ISSUE THREAD

**Issue by DuMaM** [Keeper-Security/Commander#785]
Hi,
I'm trying to log into keepersecurity.com with keeper commander. 
After pasting SSO Login URL prompted after login command. 

I get:
`{"message":"Unable to read the payload param","error":"bad_request"}`

**Comment by DuMaM** [comment]
Thanks for fast response.
The problem is, after pasting url from instructions you posted nothing really happens... 
This url is invalid to trigger okta auth, and then redirect me to keepersecurity.com
In Monday I can share with you a console output if you want.

**Comment by ladams-keeper** [comment]
@DuMaM 
Could you share the output?
Also, if you would like to setup some time to troubleshoot with the team, please send a message to: commander@keepersecurity.com

Thanks

**Comment by ladams-keeper** [comment]
@DuMaM We've improved the SSO login feature in the latest Commander release.  

Now when prompted to login with SSO, hit `o` to open a webpage to login to your SSO. Once logged in you will see a button which copies the required token to you clipboard. 
After clicking the button, enter `p` in Commander to paste the token and continue with Commander authentication.

Please install the latest Commander release to try this out.

**Comment by DuMaM** [comment]
My okta SSO still goes crazy, and it's unable to connect with generated url.
I switched to master password plus sso and it's fine by now.

**Comment by DuMaM** [comment]
One more thing I was able to login also with sso without master password.
After your upgrade support was able to track problem inside okta.
Thanks
