### ISSUE TITLE
Convert command fails when the record ID starts with "-" character.

### ISSUE THREAD

**Issue by CarlitoxxPro** [Keeper-Security/Commander#786]
As mentioned in the title the convert command trows an error "ignored explicit argument" when the records ID starts with a minus character (-) and is no way to scape that character, i've tried to put \, quoting the string, etc. and no works.

E.g:

`convert -t login --recursive -123456abcdef`
`unrecognized arguments: -123456abcdef`

`convert -t login --recursive "-123456abcdef"`
`unrecognized arguments: -123456abcdef`

`convert -t login --recursive '-123456abcdef'`
`unrecognized arguments: -123456abcdef`

`convert -t login --recursive \-123456abcdef`
`unrecognized arguments: -123456abcdef`

**Comment by ladams-keeper** [comment]
Hello,

When a UID starts with "-" you need to preface it with "--"
For example: `convert -t login --recursive -- -123456abcdef`

There is some more information in our docs: https://docs.keeper.io/secrets-manager/commander-cli/using-commander/troubleshooting-commander-cli#uid-starts-with
