### ISSUE TITLE
add --add-role to enterprise team command

### ISSUE THREAD

**Issue by mxmorin** [Keeper-Security/Commander#787]
There's no way add team to rôle with commander.
Is it possible to add --add-role option for enterprise-team command like enterprise-user command ?

**Comment by mxmorin** [comment]
See PR #789

**Comment by ladams-keeper** [comment]
@mxmorin This was added in a recent release. Please download the latest Commander release to use it.

the `enterprise-team` command now has an option `--add-role`
and the `enterprise-role `command now has an option `--add-team`
