### ISSUE TITLE
Example for creating custom fields doesn't work

### ISSUE THREAD

**Issue by mxmorin** [Keeper-Security/Commander#811]
In the documentation https://docs.keeper.io/secrets-manager/commander-cli/using-commander/command-reference/record-commands#add-command-record-types, example using custom fields doesn't work

```
add type=login title=Benefits c.text.pin=18897
Error(s) converting options to a record type: ["Invalid field value: {'text': [{'pin': '18897'}]}"]

```
Regards

**Comment by sk-keeper** [comment]
Thank you for reporting this issue.
The documentation and implementation are different. The correct command would be 
`add type=login title=Benefits c.text.label=pin c.text=18897`
