### ISSUE TITLE
How to add two custom fields of  same type

### ISSUE THREAD

**Issue by mxmorin** [Keeper-Security/Commander#812]
With add -v3d command, to create a new record with a text custom field, i have to do : 

```
My Vault> add type=login title=Benefits c.text.label="AppLogin" c.text=18897 
```
I need to add 2 customs fields so i do : 
```
My Vault> add type=login title=Benefits c.text.label="AppLogin" c.text=18897 c.text.label="AppPwd" c.text=pwd 
Got : Error(s) converting options to a record type: ["Found duplicate keys/values: [{'custom.text.label': 2}, {'custom.text': 2}]"]
```
How can i do ?

**Comment by idimov-keeper** [comment]
Use the other option `-v3d` or `--data` instead:

`add --data '{"type": "login","title": "Benefits","fields": [],"custom": [{"type": "text", "label": "AppLogin", "value": ["18897"]}, {"type": "text", "label": "AppPwd", "value": ["pwd"]}]}'`

where `-v3d` or `--data` section maps to "data": {} in record JSON and for existing record could be retrieved with `get` command `g <UID> --format=json`

**Note!** _If you are using Windows Command Prompt you have to escape all JSON double quotes properly._

**Comment by mxmorin** [comment]
An example in the add command documentation would be appreciate
