### ISSUE TITLE
Keeper API creating throttled error

### ISSUE THREAD

**Issue by Free-devleoper** [Keeper-Security/Commander#835]
I've been creating records using keeper api now it sometimes says throttled and api call fails with 500 error why it's happening anyone can explain?

**Comment by sk-keeper** [comment]
Keeper backend may fail an api call when it decides a client sends too many requests.
Starting 16.6.10 Commander tries to recover from this error by sleeping a process for 10 seconds and repeating the failed request.
The 'throttled' error is 403 though.
https://github.com/Keeper-Security/Commander/blob/96ea77c170bb01a87bf679570ba515b8e7584c69/keepercommander/rest_api.py#L180

**Comment by Free-devleoper** [comment]
So the solution would be adding a 10 seconds delay to process large number of requests
