### ISSUE TITLE
`export --format json` without file is now outputting to console then erroring on the non-existant file not existing

### ISSUE THREAD

**Issue by somewhatabstract** [Keeper-Security/Commander#852]
In 16.6.14, `keeper --config config.json export --format json` used to output to the console.

With version 16.7.6, it outputs to the console, then exits with an error because it tries to interpret `NoneType` as a file path.

`ERROR:root:An unexpected error occurred: stat: path should be string, bytes, os.PathLike or integer, not NoneType. Toggle debug to print traceback`

**Comment by sk-keeper** [comment]
Thank you for reporting this issue.
It will be fixed in the next release
https://github.com/Keeper-Security/Commander/commit/4157f159fd739bf00e99bcf7a6cbe7209406feb8

**Comment by somewhatabstract** [comment]
The linked change does not appear to affect the writing of the file, which I think is where the error is coming from. Could there by an additional change required?

**Comment by sk-keeper** [comment]
`An unexpected error occurred: stat: path should` error comes from the system os.path.isfile function
https://docs.python.org/3/library/os.path.html#os.path.isfile
when None is passed as a filename.
`export` command outputs to stdout/console when filename parameter is not specified.
This change prevents logging absolute file name when `export` outputs to the console

**Comment by somewhatabstract** [comment]
Ah! Thanks for the clarification. Really appreciate that.
