### ISSUE TITLE
Update_Record_v3 Command Issue

### ISSUE THREAD

**Issue by tcranger1** [Keeper-Security/Commander#853]
Hello,

I'm trying to update a password of an existing record using the code below with no success.  I can confirm that I am pulling the existing record with the old password, however, the update_record command is not updating the password with the new value I've defined.  Can you please let me know what I may be missing?  Thank you.

record = api.get_record(my_params,record_UUID)
record.password='NewPassword1234'
api.update_record_v3(my_params,record)

**Comment by sk-keeper** [comment]
The recommended method of modifying a record is using `RecordEditCommand`.
This command is used by Commander CLI and it hides the differences between various record types.

`
from keepercommander.commands.recordv3 import RecordEditCommand
edit_command = RecordEditCommand()
edit_command.execute(my_params, password='NewPassword1234', record= record_UUID)
`

https://github.com/Keeper-Security/Commander/blob/release/keepercommander/custom/update_password.py

**Comment by tcranger1** [comment]
That did the trick!  Thank you very much!!
