### ISSUE TITLE
how to clip-copy username(Login)

### ISSUE THREAD

**Issue by azinsharaf** [Keeper-Security/Commander#861]
Hi, Thanks for this great CLI,
How can I copy the `Login` or `URL` values into the clipboard. It seems `cc` is only copies `Password`.

**Comment by ladams-keeper** [comment]
Hi!
You can use `clipboard-copy` (`cc`) to copy the login field of a record with the following flag included:

login:
`cc --login <YOUR RECORD UID or TITLE>`

You can not currently copy the url directly with this command, however you can use `get <YOUR RECORD UID or TITLE>` to see the fields of a record, then highlight the url and right click to copy it.

You can add `--help` or `-h` to any command in commander to see all the available options for that command, or take a look at our [documentation](https://docs.keeper.io/secrets-manager/commander-cli/overview).

**Comment by azinsharaf** [comment]
awesome! thanks!
