### ISSUE TITLE
Storage of Token

### ISSUE THREAD

**Issue by mebays** [Keeper-Security/Commander#862]
I noticed when using SSO every command requires traveling to the link and getting a new token.  In many other cli tools there is usually a temporary storage for these tokens for a duration of time.  Is that possible for this?  I would like to use this for some scripting purposes on my local machine and requiring a login token after already running `keeper login` to obtain one gets to be rather annoying.

**Comment by sk-keeper** [comment]
You are looking for Persistent Login Session.
https://docs.keeper.io/secrets-manager/commander-cli/using-commander/logging-in#persistent-login-sessions
It keeps you logged after `keeper` command exits.

Example shows that inactivity timeout is set to 1 year. You probably want to set inactivity timeout to shorter period
`this-device timeout 10` sets inactivity timeout to 10 minutes. To explicitly close the session use `logout` command.

**Comment by mebays** [comment]
> You are looking for Persistent Login Session. https://docs.keeper.io/secrets-manager/commander-cli/using-commander/logging-in#persistent-login-sessions It keeps you logged after `keeper` command exits.
> 
> Example shows that inactivity timeout is set to 1 year. You probably want to set inactivity timeout to shorter period `this-device timeout 10` sets inactivity timeout to 10 minutes. To explicitly close the session use `logout` command.

Thanks this may be just what I need. I'll have to discuss with our Administrator on enabling that functionality.
