### ISSUE TITLE
how to rotate private_key, device_token, etc. stored in config file

### ISSUE THREAD

**Issue by drosile** [Keeper-Security/Commander#869]
these values seem to be auto-generated by Commander and stored in the config file. how do we rotate them in case of compromise? do we need to? do they provide any level of access on their own? the [documentation](https://docs.keeper.io/secrets-manager/commander-cli/using-commander/logging-in#config-file-options) on these fields doesn't go into depth.

**Comment by ladams-keeper** [comment]
Hello,

Authentication details are only stored in the config file if persistent login is turned on in Commander. Persistent login is turned on/off with the following command:

`this-device persistent-login on`

You can set the authentication details to automatically timeout with this command:

`this-device timeout 30d`
('30d' is 30 days, you can set to any amount.)

take a look at our documentation for more details on persistent login:[https://docs.keeper.io/secrets-manager/commander-cli/using-commander/logging-in#creating-a-persistent-login-config]( https://docs.keeper.io/secrets-manager/commander-cli/using-commander/logging-in#creating-a-persistent-login-config)

To rotate the credentials in a config file, you can simply delete the file. Commander will create new credentials the next time you login.

**Comment by drosile** [comment]
thank you!
