### ISSUE TITLE
Compliance command 'team-report' causes an error

### ISSUE THREAD

**Issue by MtlSnk** [Keeper-Security/Commander#882]
For context:
- using Windows release:
  - v16.8.1
  - v16.8.1 [msp_report pre-release](https://github.com/Keeper-Security/Commander/releases/tag/msp_report)
- logged into user with an MSP license

I logged in, ran `compliance team-report` in the MSP and the following error popped up.

```python
My Vault> compliance team-report

Traceback (most recent call last):
  File "keepercommander\cli.py", line 522, in loop
  File "keepercommander\cli.py", line 366, in do_command
  File "keepercommander\commands\compliance.py", line 74, in execute_args
  File "keepercommander\commands\base.py", line 483, in execute_args
  File "keepercommander\commands\enterprise_common.py", line 41, in execute_args
  File "keepercommander\commands\base.py", line 395, in execute_args
  File "keepercommander\commands\compliance.py", line 125, in execute
  File "keepercommander\commands\compliance.py", line 290, in generate_report_data
StopIteration
```

The error isn't present when I switch to an MC and run the command, but the data displayed isn't valid (it reports there are no teams, but the MC does contain teams).

**Comment by jerko-lenex** [comment]
I've updated to the latest version (16.8.7) and the error is no longer present. However, there's still no output from this command.

This is all I'm seeing:
```
My Vault> compliance team-report
Team Name    Shared Folder Name    Shared Folder UID    Permissions
-----------  --------------------  -------------------  -------------
```

Do I need to configure something before I can use this? (Compliance addon is enabled)

**Comment by MtlSnk** [comment]
Updating to the latest version (v16.8.7) removes this error. However, there is still no valid output from the command.

This is all I'm getting:
```python
My Vault> compliance team-report
Team Name    Shared Folder Name    Shared Folder UID    Permissions
-----------  --------------------  -------------------  -------------
```

Do I need to configure something before I can use this? (Compliance Addon is enabled)

**Comment by sk-keeper** [comment]
`compliance` command has an option `--rebuild`.
Rebuilding data for compliance report may help.

**Comment by MtlSnk** [comment]
My apologies, I'd completely forgotten about this ticket.
Using `--rebuild` doesn't help in getting output from `compliance team-report`.

When I've `debug` mode enabled, I do see the information (team UIDs and shared folder UIDs).
