### ISSUE TITLE
tab completing doesn't work with ls

### ISSUE THREAD

**Issue by groner** [Keeper-Security/Commander#883]
Typing `ls` and hitting tab does nothing. It should allow completion of folders and records.

It should probably work with `edit -r` also.

**Comment by groner** [comment]
I initially thought this was a regression of #380, but it actually doesn't work for folders or records.

**Comment by sk-keeper** [comment]
Yes, you right. It stopped working for folders as well. It will be fixed for folders.
Autocompletion for command's options is pretty big task. It's unlikely to be done.

**Comment by sk-keeper** [comment]
> Is there some other command I should be using instead?
Commander's `search` command can be used to instead  `ls -l` to display a record content.
The search string should be distinct for the record though.
In order to display secret fields (like passwords) please us `get --unmask <RECORD UID>` command.

**Comment by sk-keeper** [comment]
`ls` command autocompletion has been fixed.

**Comment by groner** [comment]
Confirmed.

Thank you!
