### ISSUE TITLE
Need a way to see previous passwords

### ISSUE THREAD

**Issue by groner** [Keeper-Security/Commander#884]
The vault web UI allows viewing previous revisions of a record without restoring. I would like similar functionality in the commander shell.

**Comment by sk-keeper** [comment]
It is `record-history` command.

**Comment by groner** [comment]
I thought that only listed who and when, but I see that `-a view` option does show previous passwords. The filter language in the help text didn't sound what I thought I was looking for.

What do you think about a revision option to `cc`?

**Comment by sk-keeper** [comment]
I'd rather added an option/action to  `record-history` command

**Comment by sk-keeper** [comment]
`--revision` or `-r` option has been added to `clipboard-copy` command.
It accepts positive and negative revisions.
Positive revision starts from the record creation, negative starts from the current record.
-1 means the previous revision
