### ISSUE TITLE
totp -p option

### ISSUE THREAD

**Issue by yphoenix** [Keeper-Security/Commander#885]
The documentation mentions the -p option to the totp command to just get the plain text version of the totp instead of the interactive display.

When I try it I get "unrecognized arguments: -p", eg:

```
keeper totp -p "foo"
```

Is there a way to just get the plain text version of a totp. I tried piping the output expecting the command to recognize the pipe and do something sensible, but it just hangs writing the interactive output to the file.

Thanks

**Comment by aaunario-keeper** [comment]
You can use the standard POSIX shell commands `yes`, `cut`, and `tail` to extract the totp for a particular record (no need to use the `-p` flag as that applies only to legacy records, which yours does not seem to be). 

In your particular case, the following command should output just the totp code to stdout (just include additional re-direction syntax if you need to output to a different destination, e.g. to a file, etc.):
`yes | keeper totp "foo" | tail -n +3 | cut -f 2`

**Comment by yphoenix** [comment]
OK I managed to get it to work with 
```
echo | keeper totp "foo" | tail -n +3 | cut -f 2
```
As all that was needed was that extra return to stop the interactive mode.

Maybe it would be a good thing to add to the docs, especially the part about -p being deprecated and here is how you do it instead.

**Comment by aaunario-keeper** [comment]
Glad you got it working, and thanks for your great input! 
We will certainly be working towards improving the documentation (and the overall usability of the product), in no small part due to contributions such as yours.

**Comment by jaredromano** [comment]
Do you by chance know a powershell equivalent to this?

**Comment by sk-keeper** [comment]
It is `Show-TwoFactorCode` or `2fa`
`"RECORD UID" | 2fa`
https://github.com/Keeper-Security/keeper-sdk-dotnet/blob/df1afb803f2de1d3394ec788225bd229a14de7ac/PowerCommander/RecordCommands.ps1#L162

**Comment by jaredromano** [comment]
> It is `Show-TwoFactorCode` or `2fa` `"RECORD UID" | 2fa` https://github.com/Keeper-Security/keeper-sdk-dotnet/blob/df1afb803f2de1d3394ec788225bd229a14de7ac/PowerCommander/RecordCommands.ps1#L162

This is only applicable if you are using the Powershell module, which I'm not. I am running commander with python. 

BTW `Show-TwoFactorCode` on the PowerShell module also doesn't work. It just returns an empty string. 

```PowerShell
kr <id here> | 2fa
``` 
returns nothing

```PowerShell
kr <id here>
``` 
returns the record


```PowerShell
keeper totp <id here>
``` 
returns the key with the countdown bar and I want to either use the `-p` flag, or use the PowerShell module, if it worked

**Comment by jaredromano** [comment]
`2fa` doesn't always work unfortunately. If I run it when powershell first opens it works. If I have to run `kr` at all in a PS session, it will complain that "getVault" failed because it is not connected. So I run kc to connect, but then `2fa` never returns anything for the rest of the PS session. 

This is especially problematic if I have a PS script because it will require me to import the module. If I do, I am required to run `kc`, so `2fa` will never return anything

**Comment by sk-keeper** [comment]
The upcoming Python's Commander release is going to extend `clipboard-copy` command with TOTP code output.
The output of `keeper cc --totp --output=stdout <id>` command could be piped

**Comment by sk-keeper** [comment]
Commander that supports `--totp` or `-t` option  has been released.

**Comment by yphoenix** [comment]
Thanks!
