### ISSUE TITLE
Feature to copy totp to clipboard

### ISSUE THREAD

**Issue by sakaru** [Keeper-Security/Commander#889]
Similar to https://github.com/Keeper-Security/Commander/issues/885, I think it would be useful to have a `--totp` option to the `clipboard-copy|cc` command. Using this option keeper would:
1. Calculate the totp code
2. Check the remaining time until expiry. If less than some value (perhaps 5 seconds), then sleep until the next expiry happens and act on the next totp code
3. Copy the totp code into the clipboard (or to stdout if `--output` says so)

Edit: Since server implementations usually allow a 20s+ buffer, don't bother with the conditional sleep logic.

**Comment by sk-keeper** [comment]
Thank you for this suggestion. The Commander team will add this feature to the next release.

**Comment by sk-keeper** [comment]
Commander 16.8.4 has been release. It adds `--totp` to `copy-clipboard` command
