### ISSUE TITLE
Teams with an internal ID beginning with "-" minus character cannot be used on commandline

### ISSUE THREAD

**Issue by HannesVo** [Keeper-Security/Commander#914]
Hello together, 

Using SCIM to syn AAD Groups we automatically create shared folder using an scheduled script. Second step is to assign the group to the shared folder using the following keeper commander commanf

sf -a grant -e "VszooA2bBY1sjVprc673xQ" -p "20 A-Case"
sf -a grant -e "-9w4vidrGelLRvoJwgkefA" -p "20 B-Case"

first line works as designed
second line does not work

it is the first case within 3 Years that an got an Keeper Team (Group) with an leading minus character.
a leading "_" and other special chars works which suggest me that the minus character seems to be interpreted as an option parameter and not as the value of an option. how can we handle this ? 

Kind regards

Environment:
Windows Server 2019
Python 3.11
Commander Version: 16.8.7
(Also testet with Commander Version: 4.x with Python 3.9)

**Comment by aaunario-keeper** [comment]
Hi,
The following version of your 2nd command should work:
`sf -a grant -e ="-9w4vidrGelLRvoJwgkefA" -p "20 B-Case"`

**Comment by ad8-bdl** [comment]
ref. https://docs.keeper.io/secrets-manager/commander-cli/troubleshooting-commander-cli#uid-starts-with
