### ISSUE TITLE
Importing JSON with the --update flag fails to add shared users to created Folders

### ISSUE THREAD

**Issue by KevinGlassDDL** [Keeper-Security/Commander#923]
Hello!

I have a legacy system that outputs a set of passwords. I use a python script to convert it to Keeper compatible JSON. Sometimes there are new sets of passwords that are mapped to new shared folders. Existing passwords are updated. Permissions for an existing set almost never changes.

I've been attempting to use the `import --update` flag to automate this. This successfully imports new passwords, updates existing passwords, and creates new shared folders.
However, the new shared folders don't get the permissions specified in the JSON "permissions" sections of the shared folder. New folders only have the owner account in the users section of the GUI.

If I import the same .json file from the Desktop App GUI the permissions specified apply correctly.

I tested this with my generated JSON and the demo JSON from this repo I see the same thing.

For now I've been manually fixing permissions in the Keeper GUI once the import is done.

**Comment by sk-keeper** [comment]
Commander has a separate command `apply-membership`. This command uses the same JSON file but updates shared folder membership only.
In general, records are imported once but shared folder permissions may need to be modified many times as users create their accounts in Keeper.

**Comment by KevinGlassDDL** [comment]
Thank you for that! I just tested and that works. I assumed `import` would work the same as the GUI import,
