### ISSUE TITLE
Sync for enterprise-* commands

### ISSUE THREAD

**Issue by ad8-bdl** [Keeper-Security/Commander#954]
When using the Enterprise Management commands, `enterprise-*`, changes that are made elsewhere, e.g. in  the web Admin console, are not reflected in the keeper shell. The user has to log exit the keeper shell and restart it in order to see the updates.

Repro:
1. open a keeper shell CLI as well as the web admin console https://keepersecurity.com/console
2. inspect a role, e.g. `enterprise-role MyRole`, note the current Role Enforcements
3. make a change to that role in the admin console
4. sync in the admin console: click the 'Full Sync' in the top-right corner
5. run `sync-down` in the keeper shell

Expect: rerunning the `enterprise-role MyRole` should show the changed role
Actual: rerunning the `enterprise-role MyRole` shows the role as it was when the shell was started

Workaround: exit the shell, restart the shell (or just run the relevant commands non-interactively)

**Comment by sk-keeper** [comment]
`sync-down` loads your vault data (records, shared folders, etc)
`enterprise-down` or `ed` s used to get your latest enterprise information.

**Comment by ad8-bdl** [comment]
Ah - great, that works.

It's missing from the documentation though: https://docs.keeper.io/enterprise-guide/user-and-team-provisioning/cli-provisioning-with-commander-sdk#keeper-command-reference
