### ISSUE TITLE
Cannot install on CentOS 7

### ISSUE THREAD

**Issue by slarti-b** [Keeper-Security/Commander#963]
I have a CentOS 7 machine.  I had keeper CLI installed and working.  I had an issue (I've now found the solution there - it was the UID starting with -) but what confused me was my get command failed (clear error message) but return value was still 0 (success).  Thought i'd update the Keeper CLI before logging a bug and now it won't run at all.  I tried upgrading, then I did `pip3 uninstall keepercommander` and re-installed following instructions at https://docs.keeper.io/secrets-manager/commander-cli/commander-installation-setup/installation-on-linux  However, when i try to run any command (or even just `keeper` without a command) i get output like

```
$ keeper --version
Traceback (most recent call last):
  File "/home/adam/.local/bin/keeper", line 5, in <module>
    from keepercommander.__main__ import main
  File "/home/adam/.local/lib/python3.6/site-packages/keepercommander/__main__.py", line 27, in <module>
    from . import cli
  File "/home/adam/.local/lib/python3.6/site-packages/keepercommander/cli.py", line 27, in <module>
    from . import api, display, loginv3, ttk
  File "/home/adam/.local/lib/python3.6/site-packages/keepercommander/api.py", line 31, in <module>
    from . import constants, rest_api, loginv3, utils, crypto, vault
  File "/home/adam/.local/lib/python3.6/site-packages/keepercommander/rest_api.py", line 23, in <module>
    from .proto import APIRequest_pb2 as proto
  File "/home/adam/.local/lib/python3.6/site-packages/keepercommander/proto/APIRequest_pb2.py", line 16, in <module>
    from . import enterprise_pb2 as enterprise__pb2
  File "/home/adam/.local/lib/python3.6/site-packages/keepercommander/proto/enterprise_pb2.py", line 20, in <module>
    _KEYTYPE = DESCRIPTOR.enum_types_by_name['KeyType']
AttributeError: 'NoneType' object has no attribute 'enum_types_by_name'
```

For info, the version i had working before I tried to upgrade reported as
```
$ keeper --version
Keeper Commander, version 16.2.2
```

I did manage to get a working version back with 
```
pip3 install --force-reinstall keepercommander==16.2.2
```
Now it reports
```
$ keeper --version
/home/adam/.local/lib/python3.6/site-packages/keepercommander/loginv3.py:16: CryptographyDeprecationWarning: Python 3.6 is no longer supported by the Python core team. Therefore, support for it is deprecated in cryptography. The next release of cryptography (40.0) will be the last to support Python 3.6.
  from cryptography.hazmat.backends import default_backend
Keeper Commander, version 16.2.2
```
So, maybe I need a newer Python 3.  Nothing on install page about that - and I have done `yum update` so I guess I have the latest version for Centos 7.  pre-requisites are just "Python 3.x".  it says "CentOS (Latest)" but 7 is the latest usable version of CentOS

Is CentOS 7 supported and what is the recommended way to get the latest version running there?

**Comment by sk-keeper** [comment]
Python 3.6 is quite an old version though still supported.
Commander 16.2.2 is pretty old version as well.
The traceback shows error outside of the Commander code. It looks like there is a conflict in some third party package
It is possible if `pip` is not current

Here are steps to install Commander with `pip`
1. Create Python virtual environment for Commander
`python3 -m venv keeper`
2. Activate newly created environment
`source ./keeper/bin/activate`
3. Run `pip list` this command will show you how to update `pip` itself
`WARNING: You are using pip version 20.1.1; however, version 23.0.1 is available.
You should consider upgrading via the '/Users/user/Work/PY/qqq/bin/python3 -m pip install --upgrade pip' command.
`
4. Upgrade `pip`
5. `pip install wheel` https://pythonwheels.com/
6. Install the latest version of Commander `pip install keepercommander`
7. Python environment needs to be activated for any new terminal
`source ./keeper/bin/activate`

**Comment by slarti-b** [comment]
> Python 3.6 is quite an old version though still supported. Commander 16.2.2 is pretty old version as well. The traceback shows error outside of the Commander code. It looks like there is a conflict in some third party package It is possible if `pip` is not current
> 
> Here are steps to install Commander with `pip`
> 
> 1. Create Python virtual environment for Commander
>    `python3 -m venv keeper`
> 2. Activate newly created environment
>    `source ./keeper/bin/activate`
> 3. Run `pip list` this command will show you how to update `pip` itself
>    `WARNING: You are using pip version 20.1.1; however, version 23.0.1 is available. You should consider upgrading via the '/Users/user/Work/PY/qqq/bin/python3 -m pip install --upgrade pip' command. `
> 4. Upgrade `pip`
> 5. `pip install wheel` https://pythonwheels.com/
> 6. Install the latest version of Commander `pip install keepercommander`
> 7. Python environment needs to be activated for any new terminal
>    `source ./keeper/bin/activate`

Yeah, 3.6 is old.  That's what CentOS (and RHEL) generally do - they run old versions and back-port the security fixes. By Design.  Often their "current" version (even on latest version of OS) is considered unsupported by the upstream maintainers, but RH back-port the security fixes so it's kind-of supported and you have to judge whether to use that or install from a third-party source to get a newer one.  And yes, CentOS 7 is also old, and we plan to upgrade, but we're looking at options given the licencing changes make newer versions unusable in the way 7 was.

I ran the pip upgrade command (as per the instructions linked in my original post) but again, it's CentOS so it's probably an old version.  It reports `pip 21.3.1`  Keeper I simply hadn't updated as it worked.  And I only use the CLI when I need to develop the deployment routines.  Will try as outlined and let you know
