### ISSUE TITLE
Please remember my 2FA code duration preference

### ISSUE THREAD

**Issue by groner** [Keeper-Security/Commander#988]

**Comment by sk-keeper** [comment]
We are not aware of any issue in this area. Can you provide more information please?

**Comment by groner** [comment]
Sure. 

This happens when using `2fa_duration=30_days` setting. After the code expires I need to reauthorize, the setting reverts to `2fa_duration=login`.

Additionally, if I put in the wrong code I wind up back at the 2FA method prompt and on returning to the TOTP menu the setting has reverted to `2fa_duration=login` again.

**Comment by sk-keeper** [comment]
Commander supports `mfa_duration` configuration file property. 
https://docs.keeper.io/secrets-manager/commander-cli/using-commander/logging-in#commander-configuration-file

The next Commander release will fix `2fa_duration` reset in case of 2fa auth failure
